### ISSUE TITLE
`postsPerPage` and pagination is broken

### ISSUE THREAD

**Issue by dariusz-wozniak** [alxshelepenok/gatsby-starter-lumen#1011]
**Describe the bug**
I tried to enlarge number of `postsPerPage` and made changes in the code, as per https://github.com/alxshelepenok/gatsby-starter-lumen/issues/660:

/config.js:

```
module.exports = {
  // ...
  postsPerPage: 400,
  // ...
};
```

/src/type/index.js:

```
export type PageContext = {
  tag: string,
  category: string,
  currentPage: number,
  prevPagePath: string,
  nextPagePath: string,
  hasPrevPage: boolean,
  hasNextPage: boolean,
  postsLimit: number,
};
```

\content\posts\:

2016-01-09---Perfecting-the-Art-of-Perfection.md
2016-01-12---The-Origins-of-Social-Stationery-Lettering.md
2016-02-02---A-Brief-History-of-Typography.md
2017-18-08---The-Birth-of-Movable-Type.md
2017-19-08---Humane-Typography-in-the-Digital-Age.md

**To Reproduce**
1. Go to the main page.

**Expected behavior**
1. All 5 posts should be visible.
2. NEXT link should be disabled.

What's more, when clicking on NEXT, I get 404 page:

```
Gatsby.js development 404 page

There's not a page yet at /page/1
```

**Screenshots**

![image](https://user-images.githubusercontent.com/5969160/141844103-070deffc-9f30-465a-9a67-c531e8f589b0.png)

**Desktop**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 94.0.1 (64-bit)

**Comment by alxshelepenok** [comment]
Thank you for your feedback. The starter has been updated to the new version and the bug has probably been fixed. Feel free to reopen the issue.
