### ISSUE TITLE
When hovering on `NEXT`, site is being scrolled to the top

### ISSUE THREAD

**Issue by dariusz-wozniak** [alxshelepenok/gatsby-starter-lumen#1012]
**Describe the bug**
When hovering on NEXT, site is being scrolled to the top. Mouse is not clicked.

**To Reproduce**
1. Go to main page.
2. Scroll down.
3. Hover on Next link.

To re-reproduce the above, refresh the website.

**Expected behavior**
Site is not being scrolled up.

**Screenshots**
![gatsby-scrolling](https://user-images.githubusercontent.com/5969160/141844802-1a42aec4-09fa-4738-9e66-e88ee3ef01b9.gif)

**Desktop**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 94.0.1 (64-bit)
 
**Remarks**
When hovering on the second time, site is not being scrolled.

**Comment by allergictobullshit** [comment]
Same issue here..

**Comment by kalinchernev** [comment]
Same issue in development, it's quite strange.

**Comment by alxshelepenok** [comment]
Thank you for your feedback. The starter has been updated to the new version and the bug has probably been fixed.
