### ISSUE TITLE
Is lumen still maintained? Can't upgrade to Gatsby v4

### ISSUE THREAD

**Issue by gkossakowski** [alxshelepenok/gatsby-starter-lumen#1015]
**Describe the bug**
I've trying to upgrade Lumen-started site to Gatsby v4 and hit numerous issues. I love lumen's aesthetics and would love to keep using it. This leads me to a question: is lumen still maintained?

**To Reproduce**
1. Create a new site out of this starter
2. Follow the official Gatsby v4 upgrade guide
3. Fix a few more obvious migration issues
4. Get stuck at:

```
failed Validating Rendering Engines - 1.332s

 ERROR #98001  WEBPACK

Built Rendering Engines failed validation failed validation.

Please open an issue with a reproduction at https://github.com/gatsbyjs/gatsby/issues/new for more help



  Error: Generated engines use disallowed import "babel-runtime/helpers/asyncToGenerator". Only allowed imports are to Node.js builtin modules or engines internals.

  - child.ts:60 Function._module.default._load
    [gkossakowski.github.io]/[gatsby]/src/utils/validate-engines/child.ts:60:11

  - loader:999 Module.require
    node:internal/modules/cjs/loader:999:19

  - helpers:102 require
    node:internal/modules/cjs/helpers:102:18

  - index.js:141170 Object.defineProperty.value
    /Users/grek/coding/gkossakowski.github.io/.cache/query-engine/index.js:141170:18
```

**Additional context**
Resolving that specific error would be great but the bigger question is whether lumen is still actively maintained?

**Comment by alxshelepenok** [comment]
Thank you for your feedback. The starter has been updated to the new version and the bug has probably been fixed.
