### ISSUE TITLE
Wrong format of math formula with gatsby-remark-katex

### ISSUE THREAD

**Issue by BigTony666** [alxshelepenok/gatsby-starter-lumen#113]
**Describe the bug**
Math formula is rendered in wrong format after adding `gatsby-remark-katex` plugin.

**To Reproduce**
1. Installing the plugin `gatsby-remark-katex`.
2. Include the katex css file in `_base.scss`:
```scss
@import "~katex/dist/katex.min.css";
```
3. Write a math formula `a + b` in markdown file:

```markdown
$a+b$
```
4. Formula is rendered in wrong format on HTML

**Screenshots**
<img width="150" alt="wrong-format" src="https://user-images.githubusercontent.com/29159357/52811655-9e76eb80-3063-11e9-852e-47494ecceb88.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by willbryk720** [comment]
I have the same problem

**Comment by alxshelepenok** [comment]
@BigTony666 @willbryk720 

You need to add changes to scss-module in the Сontent component [src/components/Post/Content/Content.module.scss](https://github.com/alxshelepenok/gatsby-starter-lumen/commit/05e6f44761a028b7982900b96a5e5550f8bc51da#diff-15f67c746c0b5819b40ed85ae57ed116)
