### ISSUE TITLE
Error while doing "npm run start"

### ISSUE THREAD

**Issue by gabrielrosset** [alxshelepenok/gatsby-starter-lumen#1151]
**Describe the bug**

npm run start get this error message:
```
> npm run clean && gatsby develop
> gatsby-starter-lumen@1.3.10 clean
> rimraf .cache public
ERROR #11901  COMPILATION
Failed to compile Gatsby files (@parcel/optimizer-terser):
You must provide the URL of lib/mappings.wasm by calling SourceMapConsumer.initialize({ 'lib/mappings.wasm': ... }) before using SourceMapConsumer.
```

**To Reproduce**
1. Clone project
2. Install NPM deps
3. Exec npm run start

**Expected behavior**
It should start

**Desktop (please complete the following information):**
 - OS: Windows 11 WSL2
 - Browser none
 - Version 1.3.10

**Additional context**
Remove package-lock.json and node_modules, then retrying npm i + npm run start fix this issue.

**Comment by alxshelepenok** [comment]
Updated lock file, I think it should work https://github.com/alxshelepenok/gatsby-starter-lumen/pull/1153
