### ISSUE TITLE
Change default orange color for links?

### ISSUE THREAD

**Issue by charles-hood** [alxshelepenok/gatsby-starter-lumen#1164]
Is there an easy way to change the default highlight color for hyperlinks?

**Comment by alxshelepenok** [comment]
The only way to do this is to change the color in the scss variables (https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/assets/scss/_variables.scss).

Or you can also add a new color to use in css variables here:
https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/assets/scss/themes/_dark.scss
https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/assets/scss/themes/_light.scss
