### ISSUE TITLE
Display page by default instead of post

### ISSUE THREAD

**Issue by charles-hood** [alxshelepenok/gatsby-starter-lumen#1165]
Is there a way I can display a static page, for example the About page, in the right content pane, by default, upon first entering the site? (Instead of posts)

**Comment by charles-hood** [comment]
Where should the index md file be located and what should it be named?
I'm getting:
NOT FOUND
You just hit a route that doesn't exist... the sadness.

**Comment by alxshelepenok** [comment]
Must be inside the `content` directory.
