### ISSUE TITLE
npm start ERROR

### ISSUE THREAD

**Issue by luckhole007** [alxshelepenok/gatsby-starter-lumen#1228]
when i run npm start then i had a following problem 

 ERROR  UNKNOWN

Missing onError handler for invocation 'building-schema', error was 'Error: Cannot create as
TypeComposer the following value:
  GraphQLScalarType({ name: "Date", description: "A date string, such as 2007-12-03, compliant
 with the ISO 8601 standard for representation of dates and times using the Gregorian
calendar.", specifiedByURL: undefined, serialize: [function String], parseValue: [function
String], parseLiteral: [function parseLiteral], extensions: {  }, astNode: undefined,
extensionASTNodes: [] }).'. Stacktrace was 'Error: Cannot create as TypeComposer the following
 value:
  GraphQLScalarType({ name: "Date", description: "A date string, such as 2007-12-03, compliant
 with the ISO 8601 standard for representation of dates and times using the Gregorian
calendar.", specifiedByURL: undefined, serialize: [function String], parseValue: [function
String], parseLiteral: [function parseLiteral], extensions: {  }, astNode: undefined,
extensionASTNodes: [] }).
    at SchemaComposer.createTempTC (/root/smutt_hole/gatsby-starter-lumen/node_modules/graphql
-compose/src/SchemaComposer.ts:624:11)
    at SchemaComposer.createTC (/root/smutt_hole/gatsby-starter-lumen/node_modules/graphql-com
pose/src/SchemaComposer.ts:580:66)
    at SchemaComposer.add (/root/smutt_hole/gatsby-starter-lumen/node_modules/graphql-compose/
src/SchemaComposer.ts:876:21)
    at createSchemaComposer (/root/smutt_hole/gatsby-starter-lumen/node_modules/gatsby/src/sch
ema/schema-composer.ts:21:18)
    at build
(/root/smutt_hole/gatsby-starter-lumen/node_modules/gatsby/src/schema/index.js:110:26)
    at buildSchema
(/root/smutt_hole/gatsby-starter-lumen/node_modules/gatsby/src/services/build-schema.ts:19:3)'

not finished building schema - 78.990s

**Comment by alxshelepenok** [comment]
Fixed:
#1231
#1229

**Comment by pabloscv** [comment]
Nice!

**Comment by luckchain007** [comment]
thank u

**Comment by luckchain007** [comment]
Thank you!
