### ISSUE TITLE
could you make easier md file ? 

### ISSUE THREAD

**Issue by umanking** [alxshelepenok/gatsby-starter-lumen#138]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

now  I'm using of this template for my blog 
but, when I make post (md file), 
I have to do a lot of things like slug & date, and description
 
Could you make easier md file (automatic)

**Comment by vzhou842** [comment]
Not sure what you're really asking for here - the required frontmatter is all pretty basic and can just be copied / pasted into new posts. You should really be setting the slug / date / description yourself, there's nothing that can be automated.

Closing for now, comment if you want to clarify.
