### ISSUE TITLE
How Can I add Icons in contact section?

### ISSUE THREAD

**Issue by dsifat** [alxshelepenok/gatsby-starter-lumen#174]
**Is your feature request related to a problem? Please describe.**
I am new to gatsby and react. I want to add icons. Like I want to add linkedin icon. What I got is icons.js where you featured some icons but there are only 5 icons. How can I add more. Please take me as novice and please help me.

**Comment by alxshelepenok** [comment]
@dsifat You can find the icon on [iconmonstr.com](https://iconmonstr.com), copy the path and  viewBox to [icons constants](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/constants/icons.js)
You also need to add linkedin to [get-contact-href.js](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/utils/get-contact-href.js) and [get-icon.js](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/utils/get-icon.js)
It seems to be all.

![Снимок экрана от 2019-04-08 18-52-35](https://user-images.githubusercontent.com/8599449/55738300-869e6100-5a2f-11e9-8958-e36e20a5ea3a.png)

![Снимок экрана от 2019-04-08 18-53-17](https://user-images.githubusercontent.com/8599449/55738349-a03fa880-5a2f-11e9-95cb-8e34824b9ad4.png)

**Comment by namdnguyen** [comment]
You will also need to update [use-site-metadata.js](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/hooks/use-site-metadata.js).
