### ISSUE TITLE
Flow typing?

### ISSUE THREAD

**Issue by vzhou842** [alxshelepenok/gatsby-starter-lumen#176]
What are your thoughts on integrating [Flow](https://flow.org/) into this project? I've begun doing it for [my own personal site](https://github.com/vzhou842/victorzhou.com) and it's pretty simple / can be done incrementally. Flow works very well with React/Jest and I'd be happy to take the lead on this endeavor if it's something you think would add value.

**Comment by alxshelepenok** [comment]
@vzhou842  I am for it
