### ISSUE TITLE
404 does not work on github pages

### ISSUE THREAD

**Issue by guilhermevrs** [alxshelepenok/gatsby-starter-lumen#219]
**Describe the bug**
When deploying to a github repository (using gh-pages), the 404 redirection does not work

**To Reproduce**
1. Start a new project using gatsby-starter-lumen
2. Add a git remote to a Github user repostory (e.g. [your-user].github.io)
3. Change the deploy script to "deploy": "yarn run clean && gatsby build && gh-pages -d public -b master",
3. Run yarn deploy
4. Try to access a wrong page (e.g. [your-user].github.io/blabla)
5. User gets redirected to Github pages default 404 page

**Expected behavior**
The user should be redirected to [your-user].github.io/404

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Additional context**
I can see the 404 folder that has been created. I wonder if it shouldn't be a 404.html in the root folder instead.
I tried as well to move the 404/index.html to ./404.html, but then the links do not work

**Comment by daniel-vera-g** [comment]
I am experiencing the same error with Github pages.

I run a `yarn build` in travis and push it to my master branch. It works fine, only the 404 pages do not work.

**Comment by guilhermevrs** [comment]
I ended up by building my own 404 banner on the index template and a 404.js in src/pages to redirect to index with a hash argument.

I also moved to netlify to ease deployment process
