### ISSUE TITLE
Question: Change the favicon

### ISSUE THREAD

**Issue by dbriesz** [alxshelepenok/gatsby-starter-lumen#241]
I’d like to change the favicon, but I’m not seeing where that’s done. Can you provide instructions on how to do that? Thanks!

**Comment by alxshelepenok** [comment]
@dbriesz you can change the favicon here: [gatsby-config.js#L174](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/gatsby-config.js#L174)

**Comment by dbriesz** [comment]
Thanks!
