### ISSUE TITLE
Warning in netlify building process when I added gatsby-remark-emoji plugin

### ISSUE THREAD

**Issue by P-iknow** [alxshelepenok/gatsby-starter-lumen#254]
**Describe the bug**
- I added gatsby-remark-emoji plugin to use emoji in my markdown. 
- In the netlify build process, I found many warnings. warning details below.
![image](https://user-images.githubusercontent.com/35516239/59148935-e920d700-8a49-11e9-8b31-d71ba39605f2.png)
- Can't I use this plug-in in lumen theme ?

**To Reproduce**
- `yarn add gatsby-remark-emoji`
-  fix `gatsby-config.js`
```js
 {
            resolve: 'gatsby-remark-emojis',
            options: {
              // Deactivate the plugin globally (default: true)
              active : true,
              // Add a custom css class
              class  : 'emoji-icon',
              // Select the size (available size: 16, 24, 32, 64)
              size   : 64,
              // Add custom styles
              styles : {
                display      : 'inline',
                margin       : '0',
                'margin-top' : '1px',
                position     : 'relative',
                top          : '5px',
                width        : '25px'
              }
            }
          },
```

**Expected behavior**
- no warning in netlify building process

**Desktop (please complete the following information):**
 - OS: Mac /  Mojave
 - Node v8.11.1

**Comment by alxshelepenok** [comment]
Hi @P-iknow, these warnings are not related to the fact that you added gatsby-remark-emoji.
https://github.com/alxshelepenok/gatsby-starter-lumen/issues/100
https://github.com/netlify/netlify-cms/issues/1678
