### ISSUE TITLE
Can I upgrade the template version?

### ISSUE THREAD

**Issue by marcus-alonso** [alxshelepenok/gatsby-starter-lumen#277]
Hi, thanks for the template, it's very helpful! 
Is it possible to upgrade the template version? As I used this starter template to start a Gatsby site like several months ago, and I found that the master branch already had some commits, and I want to use them in my project. Is there some way to do it?
Thanks!

**Comment by alxshelepenok** [comment]
@marcus-alonso Hi, yes, you can do this with `git pull` and `git fetch`.
