### ISSUE TITLE
allow users to customize path prefix

### ISSUE THREAD

**Issue by foxnewsnetwork** [alxshelepenok/gatsby-starter-lumen#281]
**Is your feature request related to a problem? Please describe.**
I'm trying to deploy a blog to github pages (i.e. xxxx.github.io/my-blog), however, there is no easy way to customize `pathPrefix`

**Describe the solution you'd like**
Add a `pathPrefix` field in `config.js` at https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/config.js#L4

**Describe alternatives you've considered**
- Using the [material starter](https://www.gatsbyjs.org/starters/Vagr9K/gatsby-material-starter/) which has this feature
- Restructuring my github page to deliver without a prefix path

**Additional context**

Here's how I would implement this feature request

- add `pathPrefix` to https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/config.js#L4
- modify `gatsby-config.js` to include the `pathPrefix` at https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/gatsby-config.js#L7
- include [url-join](https://www.npmjs.com/package/url-join) to dependencies
- modify all the gatsby functions in `/gatsby/*` so that their paths are calculated for example like:
```javascript
path: urljoin(siteConfig.url, siteConfig.pathPrefix, 'page', i -1)
```

Please let me know if this is a direction we want to go down, and I can make a PR

**Comment by alxshelepenok** [comment]
@foxnewsnetwork Hi, thanks for your offer, you can make PR
