### ISSUE TITLE
Flow Infer Error - Cannot resolve name 'describe' in test files

### ISSUE THREAD

**Issue by I-keep-trying** [alxshelepenok/gatsby-starter-lumen#289]
**Describe the bug**
I have created a brand new starter blogs, twice, once using `gatsby new` and now using the 'Deploy to Netlify' button. I have everything working, including NetlifyCMS. However, I have not done anything at all to any of the test scripts in the `templates` directory; they have not been modified in any way, but each and every one of them is giving me these types of errors: 
```
Cannot resolve name `describe`. Flow(InferError)
Cannot resolve name `beforeEach`. Flow(InferError)

```
... the same errors with `it`, `expect`, and `test`. 

I already fixed this in my previous `gatsby new` project, but now I cannot remember how I fixed it, and also, since it's happening consistently, I decided to bring it up.

**To Reproduce**

Not sure how you would reproduce this - I seem to be the only person in the world with this problem, I have spent several hours googling and I don't see anything that seems relevant. It happens immediately when I create a new instance. 

I have not changed `flowconfig.js`.

**Expected behavior**
The flow Infer error should not be happening.

**Screenshots**
![flow-error](https://user-images.githubusercontent.com/26046173/60836599-099c9800-a194-11e9-9a63-acdf5b07d090.png)

**Desktop (please complete the following information):**
Visual Studio Code, Version: 1.36.0 (user setup)
Date: 2019-07-03 T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows 10 x64 10.0.18362

**Comment by alxshelepenok** [comment]
@I-keep-trying  These errors are due to the fact that flow definitions have not been installed.
to install them, run `yarn flow-typed jest`
or add recent changes https://github.com/alxshelepenok/gatsby-starter-lumen/commit/04bb1485243e1b429e1f08fb83515ebf6d96c6ed
