### ISSUE TITLE
gatsby-remark-images not work

### ISSUE THREAD

**Issue by wuuhw** [alxshelepenok/gatsby-starter-lumen#300]
I found this plugin is not running,
`gatsby-remark-images` 
see  [line number](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-remark-images/src/constants.js#L11)
pugin will added  attribute＂gatsby-resp-image-image＂ to the img, but now it looks better than no,

**Comment by alxshelepenok** [comment]
@wuuhw Thanks for noticing. Fixed https://github.com/alxshelepenok/gatsby-starter-lumen/commit/babcddb3a27e8590bb7829b9a22f9d6cfef59ca0
