### ISSUE TITLE
KaTeX font face styles are included in every html pages, even if it don't use KaTeX

### ISSUE THREAD

**Issue by xPixv** [alxshelepenok/gatsby-starter-lumen#301]
**Is your feature request related to a problem? Please describe.**
KaTeX font face styles in every pages
It cause every html files are more than 100KB, even if 404 page

**Describe the solution you'd like**
Is there a way that add KaTeX font face on demand. Do not included in pages that do not use it.

**Describe alternatives you've considered**
Maybe can add a meta prop to tell compiler use KaTeX or not.

**Additional context**
![image](https://user-images.githubusercontent.com/9652227/61179645-781ca280-a639-11e9-88ac-d44e5b1ac7f5.png)

**Comment by alxshelepenok** [comment]
@xPixv Thanks for your issue, fixed in https://github.com/alxshelepenok/gatsby-starter-lumen/commit/d5d6b2bf50894c8450f28f32b8133b8b0a750be7

A new option has been added to the config that disables the katex styles. Unfortunately, I could not turn them off on specific pages.

**Comment by xPixv** [comment]
Thank you a lot! :)
