### ISSUE TITLE
Allow to use ReactJs Component in post markdown(.md) files

### ISSUE THREAD

**Issue by atapas** [alxshelepenok/gatsby-starter-lumen#302]
**Is your feature request related to a problem? Please describe.**
This is a wonderful startup project that given ability to write blog posts using the .md files. I would like to include a react component like how I am able to include and html tags.

**Describe the solution you'd like**
This will help me to include a React component directly and run on by blog post.

Something like this:
```javascript
import { Test } from '../components/test'
<Test />
```
I have seen the Gatsby MDX file supports mixing the JSX and MD content. It will be immensely useful.

https://github.com/mdx-js/mdx

In my blog post site, I would like to use this template and when user click on a post to see details, they will see the details along with a working example(this will be the related ReactJs component)

**Describe alternatives you've considered**
No Alternates available

**Additional context**
NA

**Comment by miku86** [comment]
This would be a fantastic feature.

Example: I want to add contact data in a page.
If I could use JavaScript in the page,
I could use data from `config.js` by using `getContactHref()`.

**Comment by alxshelepenok** [comment]
It can not all be useful, so let's keep it simple and leave just markdown.
