### ISSUE TITLE
The sidebar moves slightly when paging. 

### ISSUE THREAD

**Issue by stigrune** [alxshelepenok/gatsby-starter-lumen#328]
**Describe the bug**
The sidebar moves slightly when paging. 

**To Reproduce**
1. Go to https://lumen.netlify.com/
2. Click on '→ NEXT'
3. Click on '← PREV'

**Expected behavior**
Sidebar stays in fixed position. 

**Screenshots**
![lumen-bug](https://user-images.githubusercontent.com/1052748/62146796-648a6080-b2f6-11e9-8bdc-7065a2f00cec.gif)

**Desktop:**
 - OS: Windows 10
 - Browser: 
    - Google Chrome 75.0.3770.142
    - Microsoft Edge 42.17134.1.0
    - Firefox 68.0.1

**Comment by stigrune** [comment]
Just noticed that all the content in the sidebar is moving a bit, not just the line.

**Comment by nicholaspung** [comment]
I believe this has something to do with the scrollbar activating and deactivating.

**Comment by alehel** [comment]
There is actually a pretty easy CSS fix for this. 

```css
html {
  margin-left: calc(100vw - 100%);
}
```

There is a codepen I found online demonstrating it here: https://codepen.io/elstgav/pen/myEJNv
