### ISSUE TITLE
Add support for SVG minification?

### ISSUE THREAD

**Issue by vzhou842** [alxshelepenok/gatsby-starter-lumen#333]
[My personal blog](https://github.com/vzhou842/victorzhou.com), which is based on this starter, uses a lot of SVGs, so I created [gatsby-plugin-optimize-svgs](https://github.com/vzhou842/gatsby-plugin-optimize-svgs) to automatically minify SVGs at build time. This minification is quite significant - see screenshot below.

<img width="861" alt="Screen Shot 2019-07-31 at 7 08 27 PM" src="https://user-images.githubusercontent.com/10209814/62254302-a1258d00-b3c6-11e9-8f54-e35f9b625d25.png">

I've had this live in production for a while and have had no issues. I'm wondering if this would be a good addition to `gatsby-starter-lumen`? A lot of sites use SVGs for icons / drawings / illustrations, and my guess is that the majority of them are not optimized. This plugin would be a lightweight addition to this starter - it does nothing if you have no SVGs, and it automatically minifies them if you do.

@alxshelepenok thoughts? I'm happy to submit a PR for this if you're onboard.

**Comment by vzhou842** [comment]
Blog post on minifying SVGs for some more context: https://victorzhou.com/blog/minify-svgs/

**Comment by alxshelepenok** [comment]
@vzhou842 Well, let's try to add. Although it will not greatly affect, since the svg-files are not used.
