### ISSUE TITLE
When going to admin: Failed to load settings from /.netlify/identity

### ISSUE THREAD

**Issue by Migacz85** [alxshelepenok/gatsby-starter-lumen#339]
**Describe the bug**
Is probably not a bug - rather jsut a configuration problems. 

**To Reproduce**
1. In url go to '/admin'
2. Click on login

` Failed to load settings from /.netlify/identity`

**Comment by alxshelepenok** [comment]
Hi @Migacz85, it seems you need to enable Identity in Netlify settings.

**Comment by Migacz85** [comment]
Yup that is right. Working now. Thank You.
