### ISSUE TITLE
Long strings in code blocks causing horizontal scrolling

### ISSUE THREAD

**Issue by jderdock** [alxshelepenok/gatsby-starter-lumen#358]
**Describe the bug**
A long string in a `<code>` block doesn't get the horizontal scroll bar that Prism JS code blocks are supposed to have. 

**To Reproduce**
1. put a long string of code in a `<code>` block
2. observe string causing horizontal scrolling (not in the PrismJS code block window)

**Expected behavior**
Long strings in code blocks should trigger a horizontal scrolling bar for just the code block to prevent the viewport from receiving a horizontal scroll bar instead.  

**Desktop**
 - OS: MacOS, iOS
 - Chrome, Safari, Firefox

**Comment by alehel** [comment]
Hmm. I'm not seeing this myself. It's working as expected on my own site. Do you have an online blog we're we can see this problem?

**Comment by jderdock** [comment]
Sure, see step 5 here:

https://www.derdock.com/posts/how-to-migrate-from-expressionengine5-to-craft/

**Comment by alxshelepenok** [comment]
@jderdock You can use  `<pre><code></code><pre>` if you want to put a lot of code.

````
```
artist_story_image>
 ![CDATA[/images/artiststoryimages/image-name.jpg]]> 
/artist_story_image>
```
````

**Comment by jderdock** [comment]
weird, i can't get it to work. can you link me to your own site? Googled and I can't find it. I appreciate you looking into it.

**Comment by kayx23** [comment]
I tried the solutions above but still have the same issue. What am I doing wrong?

![image](https://github.com/alxshelepenok/gatsby-starter-lumen/assets/39619599/74eb8107-432a-4205-922e-63a5d94b0c51)

![image](https://github.com/alxshelepenok/gatsby-starter-lumen/assets/39619599/4aad10d0-e97e-4d60-83a0-678369f31aec)
