### ISSUE TITLE
Will this starter be upgraded to Gatsby 1.0?

### ISSUE THREAD

**Issue by ZacharyChim** [alxshelepenok/gatsby-starter-lumen#37]
This is the best starter for a blog, it would be great if it will be upgraded to work with 1.0.

**Comment by alxshelepenok** [comment]
@ZacharyChim Hi, The starter was upgraded to Gatsby 1.8.12 https://github.com/alxshelepenok/gatsby-starter-lumen/releases/tag/2.0
