### ISSUE TITLE
Any interest for additional contact icons?

### ISSUE THREAD

**Issue by alehel** [alxshelepenok/gatsby-starter-lumen#371]
I was wondering if there was any interest from the dev in having additional contact icons added to the project code? Given how easy it is to turn each one "off" by simply leaving the string empty in config.js, I figured it might be an advantage to have more options? That way users won't have to go out looking for icons on their own. One could even leave them with empty strings so they don't show up by default in the starter template.

I was thinking perhaps icons for services such as LinkedIn, Instagram and gitlab to start, and more if anyone can think of ones that might be of interest. I'd be happy to do the work, update the tests and submit a pull request if this is of interest.

**Comment by alxshelepenok** [comment]
Ok, let's try adding. On average, one icon will occupy a little less than 1kb. I also propose adding Line, Weibo, WeChat, as many may use them.

**Comment by alehel** [comment]
Sounds good. I'll add a few tonight/tomorrow and then do a pull request :).

**Comment by alehel** [comment]
So far I've added LinkedIn, Instagram and Line. I was unable to find out how to link to a WeChat account, I'll try and Google it some more.

As for GitLab and Weibo there were no icons on iconmonstr for them. Are there rules for where we should be sourcing icons from?

I also noticed that there is already a Facebook icon in the icons.js file, but its not used anywhere else, so I added the missing code to enable it.

**Comment by alxshelepenok** [comment]
@alehel
> As for GitLab and Weibo there were no icons on iconmonstr for them. Are there rules for where we should be sourcing icons from?

I think the main thing is that they coincide in size and proportion.
For weibo and gitlab, you can try these icons:
https://icons8.com/icon/32918/weibo
https://icons8.com/icon/41127/gitlab

**Comment by alehel** [comment]
I sent inn a pr. I made a mistake when updating the tests, but fixed it afterwards. Made for a bit of a messy pr though. Sorry about that.

**Comment by FitzyCodesThings** [comment]
Hello! Just started using the template (perfect for what I was after), but I'm missing a couple of icons I'd like to use.

I need the Dev.to icon and Twitch - any chance of getting those added (or a pointer in the right direction to add them myself)? I'm a 100% novice to Gatsby, React, and most modern front end stuff in general, so I'm a bit nervous to do it myself.
