### ISSUE TITLE
[Config Validation]: "title" is required,    gatsby-plugin-feed

### ISSUE THREAD

**Issue by alehel** [alxshelepenok/gatsby-starter-lumen#373]
**Describe the bug**
I've had this problem for a little over a day.

With a fresh clone of the project, I get the following error message when running gatsby develop.

```
ERROR #11321  PLUGIN

"gatsby-plugin-feed" threw an error while running the onPreBootstrap lifecycle:
[Config Validation]: "title" is required

Error: [Config Validation]: "title" is required

  - gatsby-node.js:84 _callee$
    [gatsby-starter-lumen-fork]/[gatsby-plugin-feed]/gatsby-node.js:84:19
```

**To Reproduce**
1. Clone master
2. run gatsby develop

**Screenshots**
![image](https://user-images.githubusercontent.com/22277624/63637511-12322a80-c67d-11e9-8f78-ef6e2d25517a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
This problem has been there since before the PR I did earlier today. I've been trying to figure out the problem on my own, but haven't been able to figure it out.

**Comment by alxshelepenok** [comment]
I think this is due to a recent update: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-feed/CHANGELOG.md#238-2019-08-23
to fix this you need to add `title: siteConfig.title` to `gatsby-plugin-feed` in gatsby-config.js

**Comment by alxshelepenok** [comment]
However, building on netlify is now successful, as version for gatsby-plugin-feed is ^2.3.6 https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/package.json#L47

**Comment by alehel** [comment]
> However, building on netlify is now successful, as version for gatsby-plugin-feed is ^2.3.6 https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/package.json#L47

Deploying to Github pages fails without the fix. I've got version 2.3.8 of the plugin.
