### ISSUE TITLE
Build process has broken

### ISSUE THREAD

**Issue by emaren84** [alxshelepenok/gatsby-starter-lumen#41]
I am considering this starter project for rebuilding my blog. after I got this repo cloned and run the command `yarn develop`, something weird happened.

<img width="921" alt="screen shot 2017-09-12 at 23 22 47" src="https://user-images.githubusercontent.com/14539203/30330917-5104f234-9811-11e7-97bc-a3008acd5a6d.png">

Current version of yarn is `1.0.1` and gatsby-cli is `1.1.6`. (latest versions)
Please check this issue and it would be greatful if there is anything I can research for.

**Comment by emaren84** [comment]
@vinnymac Thank you for the comment. I will recheck this issue and post again on [yarn's issue page](https://github.com/yarnpkg/yarn/issues)

**Comment by nickytonline** [comment]
@emaren, I have the same issue, so I tried using npm (v 3.10.10) instead, but the same error occurs. I will try downgrading yarn for now, but it seems weird that it doesn't work with npm either.

**Comment by nickytonline** [comment]
Downgrading yarn to 0.24.6 works. Just make sure to clean your node_modules and then run `yarn` and then `yarn develop`

**Comment by codejet** [comment]
Any news on this? Couldn't find an on yarn's issue page, but maybe I missed it.

**Comment by alxshelepenok** [comment]
After adding the url-loader to the package.json, the bug was fixed.
