### ISSUE TITLE
Link on 404 page is not working

### ISSUE THREAD

**Issue by ybbarng** [alxshelepenok/gatsby-starter-lumen#46]
Hello,
I am developing my own blog based on this theme. Thank you for your cool theme.
I found that links in 404 page are not working.

Steps
1. Move to [non-exist page](https://lumen.netlify.com/asdf).
2. Click any link on that page (John Doe, Articles, About me, Contactt me)
3. Following error is occurred and the link is not working.
```
production-app.js:49 Uncaught TypeError: Cannot read property 'push' of undefined
    at eventHandler (production-app.js:49)
    at mitt.js:1
    at Array.map (<anonymous>)
    at Object.emit (mitt.js:1)
    at done (loader.js:284)
    at loader.js:302
    at loader.js:95
    at loader.js:78
    at index.json?832c:11
    at handler (patch.js:18)
```
Thank you

**Comment by alxshelepenok** [comment]
Hello @ybbarng , this bug is discussed here:
https://github.com/gatsbyjs/gatsby/issues/1838
https://github.com/gatsbyjs/gatsby/pull/2667

**Comment by ybbarng** [comment]
Oh, it is not a bug of this theme. Thanks.
