### ISSUE TITLE
Show sidebar on home page only

### ISSUE THREAD

**Issue by kenold** [alxshelepenok/gatsby-starter-lumen#464]
Is there a way to exclude the sidebar from the pagination page?

**Comment by alxshelepenok** [comment]
I think that yes, you can write such a condition to check the current page for index-template (https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/templates/index-template.js#L34):

```
{currentPage === 0 &&
   <Sidebar isIndex />
}
```
