### ISSUE TITLE
AddThis Support

### ISSUE THREAD

**Issue by ismailsunni** [alxshelepenok/gatsby-starter-lumen#478]
**Is your feature request related to a problem? Please describe.**
I tried to add a share button for each post to social media. One of the solutions would be using [AddThis](https://www.addthis.com/), it's a service (like Disqus) but for sharing button. It will be useful for a blog to have this share button so that the visitor can share a post easily from the post or page.

**Describe the solution you'd like**
It would be great if we can add our AddThis code just like we do with Disqus and google analytic in the config then it will show up automatically.

**Describe alternatives you've considered**
I tried to follow this article https://blog.alexanderwolf.tech/how-to-add-share-button-to-gatsby-blog/, but unfortunately, my skill in Gatsby is limited (in React also). I tried to find this html.js, but I couldn't find it in lumen. Perhaps you can give me some hint for it.

Thanks for the great starter!!! I like it.

**Comment by alxshelepenok** [comment]
@ismailsunni Thanks, I think you can create html.js if necessary. And then he will be involved in the build time. 

But if you do, it can be assumed that the script will be loaded on all pages.
Here is an alternative: https://github.com/garrynsk/gatsby-seo-starter/blob/031d88408dd95825ded313b60651d34eafd05378/src/templates/post.tsx#L98
