### ISSUE TITLE
Special Polish chars not rendered correctly

### ISSUE THREAD

**Issue by jedrus2000** [alxshelepenok/gatsby-starter-lumen#48]
Hello,

In fact it is issue with used Roboto fonts i think. Just I'am posting here to warn you how special Polish chars looks ugly (both same on Chrome and Firefox).
![image](https://user-images.githubusercontent.com/22714418/33232222-7d09d478-d202-11e7-9d12-20c0054cb02b.png)

Finally I've replaced it myself with ["Open Sans"](https://www.fontsquirrel.com/fonts/open-sans)

**Comment by alxshelepenok** [comment]
Hello @jedrus2000,
Now you can add any font from Google Fonts - https://github.com/alxshelepenok/gatsby-starter-lumen/commit/9cf753b94b330bc22ff5570e89074850bb8d243e

**Comment by jedrus2000** [comment]
Thanks, great, will try. 
Interesting is that this font looks now ok on Firefox (57.0.4 (64-bit) Linux)
