### ISSUE TITLE
',' appears as 'undefined' in the inline code block of the markdown file.

### ISSUE THREAD

**Issue by lxxjn0** [alxshelepenok/gatsby-starter-lumen#518]
',(comma)' appears as 'undefined' in the inline code block of the markdown file.

this is my markdown code.
![image](https://user-images.githubusercontent.com/48052622/71521927-00e87b80-2906-11ea-8e93-eee8d38a5ecd.png)

and this is what i see on my blog.
![image](https://user-images.githubusercontent.com/48052622/71521992-44db8080-2906-11ea-80e7-ec723dd5154a.png)

,(comma) is converted to that format.

**Comment by alxshelepenok** [comment]
@lxxjn0 Unfortunately, I have not been able to reproduce this yet. Which version of Gatsby are you using?

![1](https://user-images.githubusercontent.com/8599449/71778745-c4cab000-2fc2-11ea-9526-5f26ae11637a.png)

**Comment by lxxjn0** [comment]
![image](https://user-images.githubusercontent.com/48052622/71972083-53536180-324f-11ea-9aa0-ab217a35671a.png)

I use this version.
