### ISSUE TITLE
Feature: Add Twitter, OpenGraph and JSON LD metadata

### ISSUE THREAD

**Issue by madcatsu** [alxshelepenok/gatsby-starter-lumen#52]
**Feature spec:** Request to add SEO metadata to fill out Lumen features for a starter blog

**Justification:** Lumen theme already provides most blog requirements out of the box but does not support rich metadata for social sharing

**Additional info:** By example, [@cherihung's](https://github.com/cherihung) current starter [linked here](https://github.com/cherihung/gatsby-starter-foundation/blob/master/src/components/SEO/SEO.jsx) currently implements this.

**Comment by alxshelepenok** [comment]
Hello, @madcatsu, it's a good idea!
It would be cool if you add this feature.

**Comment by alxshelepenok** [comment]
@mariolopjr Yeah, you can start working on it, if you want to
