### ISSUE TITLE
netlify.toml specification causes an error when deploying to Netlify

### ISSUE THREAD

**Issue by jeffrey-hui** [alxshelepenok/gatsby-starter-lumen#528]
**Describe the bug**
Using `yarn`  in `netlify.toml` to build during a deploy on Netlify causes the deploy to fail.

```toml
[build]
  publish = "public"
  command = "yarn build"
```

**To Reproduce**

Clone the repo, deploy to Netlify via Github

**Screenshots**
Error message in Netlify deploy log:
```
5:28:38 AM: Finished saving boot dependencies
5:28:38 AM: Started saving go dependencies
5:28:38 AM: Finished saving go dependencies
5:28:41 AM: Error running command: Build script returned non-zero exit code: 127
5:28:41 AM: Failing build: Failed to build site
5:28:41 AM: failed during stage 'building site': Build script returned non-zero exit code: 127
5:28:41 AM: Finished processing build request in 1m43.431255202s
```

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser: Chrome
 - Version: 79.0.3945.88 (Official Build) (64-bit)

**My attempt at a fix**
I modified the `.toml` file to build with `npm build` instead 
```toml
[build]
  publish = "public"
  command = "npm build"
```
This allows the site to build and deploy successfully on Netlify, however, this configuration breaks `gatsby develop`.

I wanted to open an issue in case anyone else was also facing this issue. I'm looking further for a fix or it could be a Netlify configuration issue. Will update when I have a bit more info.

**Comment by davidrft** [comment]
I think it would be better if you used `gatsby build` instead of `npm build`

**Comment by mcalus3** [comment]
I also had the same problem, your suggestion helped me to fix it.

**Comment by sayfulloev** [comment]
I fixed it by adding `npm install yarn`

```
[build]
  publish = "public"
  command = "npm install yarn && npm run build"
```

**Comment by sayfulloev** [comment]
well, after adding `yarn.lock` file and removing `npm install yarn` my netlify builds are working just fine and netlify is installing yarn.

**Comment by trinwin** [comment]
I added yarn.lock and change the command to "gatsby build" and deploy successfully.
