### ISSUE TITLE
Bug: npm install error - MSB3428 Could not load the Visual C++ component VCBuild.exe 

### ISSUE THREAD

**Issue by mtrivera** [alxshelepenok/gatsby-starter-lumen#53]
Ran into this issue while trying to install on Windows 10. The following command solved the issue:

`npm install --global --production windows-build-tools`

**Comment by alxshelepenok** [comment]
More details here: [Gatsby on Windows](https://www.gatsbyjs.org/docs/gatsby-on-windows/)
