### ISSUE TITLE
Add Latex integration for blogs

### ISSUE THREAD

**Issue by eleijonmarck** [alxshelepenok/gatsby-starter-lumen#531]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In my blogs I would like to use Latex equations and to be rendered using Mathtex or katex equivalent.

```md
$$
y = x
$$

hello $x$

# title
```

**Describe alternatives you've considered**
Trying to add it myself. But hard time finding where to add it.

**Additional context**
N/A

**Comment by eleijonmarck** [comment]
Solved via import the katex library in 

`gatsby-starter-lumen/src/assets/scss/_base.scss`

```javascript
...
@import "~katex/dist/katex.min.css";
...
```

See the closed issue:
https://github.com/alxshelepenok/gatsby-starter-lumen/issues/113#issuecomment-463835007

**Comment by alxshelepenok** [comment]
@eleijonmarck Katex stylesheet is disabled by default, but you can enable it in the config https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/config.js#L12
