### ISSUE TITLE
How to use disqus

### ISSUE THREAD

**Issue by leonbec** [alxshelepenok/gatsby-starter-lumen#58]
Hi, I didn't find how to use disqus in the post page, can you help me please
![image](https://user-images.githubusercontent.com/28700378/36639685-2bbd7120-1a77-11e8-8d71-5faf2dd7536d.png)

**Comment by alxshelepenok** [comment]
@leonbec Hi, you need to add a Disqus shortname in your gatsby-config (https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/gatsby-config.js#L7)
