### ISSUE TITLE
Question: How to change the routing?

### ISSUE THREAD

**Issue by shangyusu** [alxshelepenok/gatsby-starter-lumen#62]
Thanks for this awesome project, could you please provide some quick hints to change the routing? For example, make 'about me' to be the homepage, whose path is '/'.
Thanks again!

**Comment by shangyusu** [comment]
or make the current 'articles' page (which is the home page) to be a page under pages/ ?

**Comment by chmac** [comment]
You can edit the menu in `gatsby-config.js`. The site is setup around the concept of pages and posts. So making the `about` page into the homepage would require some tweaking I guess. The homepage is rendered from `src/pages/index.jsx` while the other pages are created in `gatsby-node.js`. You could probably delete `src/pages/index.jsx` and then edit the `about` page to have the path `/`. Not 100% if that will work, but I see no reason why it wouldn't...

**Comment by skyquartam** [comment]
Hi, I want to do the exact thing, but it seems the project is really different now, how can i achieve this?

**Comment by jonmountjoy** [comment]
It is possible by doing something like the following:

* modify `create-post-pages` to prevent it from creating something on `/`.  For example, replace 

```
path: i === 0 ? '/' : `/page/${i}` 
```

with 

```
path: `/page/${i}`,
```

* modify `create-pages` to modify the path of one of the pages to `/`.  Here's the snippet I used, 

        if (_.get(edge, 'node.frontmatter.template') === 'page') {
          // if a slug matches, rewrite its path to "/"
          const slugToUse = edge.node.fields.slug === "/pages/" ? "/" : edge.node.fields.slug;
          createPage({
            path: slugToUse,
            component: path.resolve('./src/templates/page-template.js'),
            context: { slug: edge.node.fields.slug }
          });
    }

The `slug==="/pages"/` actually matches a markdown file if you name that file "index.md" and have it in your `content/pages` directory.

**Comment by transedward** [comment]
I tried what @jonmountjoy suggested but didin't work. Any other solutions that people tried might work or possible solution? @alxshelepenok, Thanks for this great repo!

**Comment by bg43179** [comment]
What @jonmountjoy suggested actually worked for me. 
In order to get the `about me` page rendered as index page, I also modufied `create-pages.js` with
```javascript
createPage({
  path: '/',
  component: path.resolve('....whatever path for the about me component')
})
```
