### ISSUE TITLE
Tips for Gatsby v2

### ISSUE THREAD

**Issue by chmac** [alxshelepenok/gatsby-starter-lumen#65]
I realise it's a while away, but I've been working on a Gatsby v2 compatible version of this starter. You can check it out here:
https://github.com/GatsbyCentral/gatsby-starter-lumen/tree/gatsby-v2

I'm working on a site with 3.5k pages and so I need the json loader stuff that @pieh has been working on for v2. The branch might help if you come to update this starter for v2 at some point.

**Comment by danielsiwiec** [comment]
I like your starter and use it for my personal [site](https://dansiwiec.com/). Any chance the migration to v2 will continue?

**Comment by chmac** [comment]
At a guess I'd say that this starter is probably not actively maintained. It looks like the last commit was in Feb 2018 and there don't seem to be any recent issue replies or PR merges from @alxshelepenok.

You could use our v2 fork as a starting point to get this running with v2.

https://github.com/GatsbyCentral/gatsby-starter-lumen/tree/gatsby-v2

**Comment by MartinRosenberg** [comment]
@chmac, would you mind getting Issues enabled for that fork? And submitting this to the [official starter repository](https://www.gatsbyjs.org/starters/)? They only list this, not your fork, so they have it under v1. I almost didn't even look at the v1 options.

Also, the fork's README.md still says to use [_this_ URL](https://github.com/alxshelepenok/gatsby-starter-lumen).

**Comment by chmac** [comment]
@MartinRosenberg Good idea, thanks for the heads up. I will do so in the next week or so. 👍

**Comment by chmac** [comment]
@MartinRosenberg The v2 edition has been [submitted](https://github.com/gatsbyjs/gatsby/pull/9215) to the starters list, and the fork has issues enabled. I've also merged a PR which made some changes (I think we're fully v2 compatible now) and updated the readme, etc. Thanks for the push.
