### ISSUE TITLE
Unable to build on Zeit platform

### ISSUE THREAD

**Issue by ujovlado** [alxshelepenok/gatsby-starter-lumen#654]
**Describe the bug**

Build fails on Zeit platform becasue it is unable to find `css` files.

```
08:50:08.154   ERROR
08:50:08.154  The path passed to gatsby-source-filesystem does not exist on your file system:
08:50:08.154  /zeit/9c5038d/static/css
08:50:08.154  Please pick a path to an existing directory.
08:50:08.154  See docs here - https://www.gatsbyjs.org/packages/gatsby-source-filesystem/
08:50:08.157  not finished source and transform nodes - 0.299s
```
It looks like the Zeit cleans the working directory before the build or prepares build files using `git archive`.

The change was introduced in this commit https://github.com/alxshelepenok/gatsby-starter-lumen/commit/d5d6b2bf50894c8450f28f32b8133b8b0a750be7

**To Reproduce**

1. Go to Zeit platform
2. Try to build site

**Expected behavior**

Build will not fail on missing css files.

**Fix**

Following change fixed it:

```diff
diff --git a/.gitattributes b/.gitattributes
index f3b1a82..d1a0f6a 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -3,4 +3,3 @@
 /.editorconfig export-ignore
 /.travis.yml export-ignore
 **/*.js.snap export-ignore
-/static/css export-ignore
\ No newline at end of file
```

**Comment by KushibikiMashu** [comment]
Same here on [Vercel](https://vercel.com/).

```
06:29:50.644  
The path passed to gatsby-source-filesystem does not exist on your file system:
06:29:50.644  
/zeit/6c15c999/static/css
06:29:50.644  
Please pick a path to an existing directory.
06:29:50.644  
See docs here - https://www.gatsbyjs.org/packages/gatsby-source-filesystem/
```

The root problem is that Vercel cannot pull `static/css` directory if the line above is in `.gitattributes`.

![image](https://user-images.githubusercontent.com/36080801/80892884-8f339a80-8d08-11ea-869c-78ed60973a7e.png)

I solved this by removing `/static/css export-ignore` from `.gitattributes`.

I'd like to know why this line was added. Should I open a PR?
