### ISSUE TITLE
Clash between prettier and eslint settings

### ISSUE THREAD

**Issue by chmac** [alxshelepenok/gatsby-starter-lumen#67]
It seems like there's a clash between the prettier and eslint settings.

For example, `.prettierrc` has:

```es6
  "trailingComma": "es5",
```

While `.eslintrc` has:

```es6
        "comma-dangle": ["error", "never"],
```

I'm not familiar enough with eslint to know how to quickly fix these issues. Maybe we need to drop the `airbnb` style guide as it doesn't play nicely with these prettier settings?

**Comment by chmac** [comment]
Hmm, having said that, I made a couple of quick "hope for the best" changes in `.eslintrc` and that seems to have killed most (maybe all) of the eslint errors I was seeing.

Would you like a PR with the changes?

**Comment by Tom-Bonnike** [comment]
You might want to take a look at https://github.com/prettier/eslint-config-prettier.

**Comment by chmac** [comment]
@Tom-Bonnike Any idea how `eslint-config-prettier` plays with `.prettierrc`?

I tried extending the `prettier` eslint settings and it seems to have solved my eslint issues. Waiting to hear from @alxshelepenok to see if they want a PR...
