### ISSUE TITLE
Error pushing to remote repository at git@github.com:[account]/[repo]

### ISSUE THREAD

**Issue by paduchurikowsik** [alxshelepenok/gatsby-starter-lumen#678]
**Describe the bug**
10:15:31 AM: Build ready to start
10:15:33 AM: build-image version: 30f629161c0736b1a3ecd8b418e5eeffab5c0faf
10:15:33 AM: build-image tag: v3.3.14
10:15:33 AM: buildbot version: 80440c4491d323247b9d55f7bea2ea6bc96ce8d2
10:15:33 AM: Fetching cached dependencies
10:15:33 AM: Failed to fetch cache, continuing with build
10:15:33 AM: Starting to prepare the repo for build
10:15:33 AM: No cached dependencies found. Cloning fresh repo
10:15:33 AM: git clone https://github.com/alxshelepenok/gatsby-starter-lumen
10:15:37 AM: Preparing Git Reference refs/heads/master
10:15:38 AM: Found Netlify configuration file netlify.toml in site root
10:15:38 AM: Found Netlify configuration file(s). Overriding site configuration
10:15:38 AM: Starting build script
10:15:38 AM: Installing dependencies
10:15:39 AM: v10.20.1 is already installed.
10:15:40 AM: Now using node v10.20.1 (npm v6.14.4)
10:15:40 AM: Started restoring cached build plugins
10:15:40 AM: Finished restoring cached build plugins
10:15:40 AM: Attempting ruby version 2.6.2, read from environment
10:15:42 AM: Using ruby version 2.6.2
10:15:43 AM: Using PHP version 5.6
10:15:43 AM: 5.2 is already installed.
10:15:43 AM: Using Swift version 5.2
10:15:43 AM: Started restoring cached node modules
10:15:43 AM: Finished restoring cached node modules
10:15:43 AM: Started restoring cached yarn cache
10:15:43 AM: Finished restoring cached yarn cache
10:15:43 AM: Installing yarn at version 1.3.2
10:15:43 AM: Installing Yarn!
10:15:43 AM: > Downloading tarball...
10:15:43 AM: [1/2]: https://yarnpk
10:15:43 AM: g.com/downloads/1.3.2/yarn-v1.3.2.tar.gz --> /tmp/yarn.tar.gz.EU3hEijb6R
10:15:43 AM:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
10:15:43 AM:                                  Dload  Uploa
10:15:43 AM: d   Total   Spent    Left  Speed
10:15:43 AM: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
10:15:43 AM: 
100    78  100    78    0     0    220      0 --:--:-- --:--:-- --:--:--   220
10:15:43 AM: 
  0     0
10:15:43 AM:  0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
10:15:43 AM: 
100    91  100    91    0     0    129      0 --:--:--
10:15:43 AM:  --:--:-- --:--:--   654
10:15:44 AM: 
100   629  100   629    0     0    570      0  0:00:
10:15:44 AM: 01  0:00:01 --:--:--   570
10:15:44 AM: 
  0  865k    0     0    0     0      0      0 --:--:--  0:00:01 --:--
10:15:44 AM: :--     0
10:15:45 AM: 
100  865k  100  865k    0     0
10:15:45 AM:  464k      0  0:00:01  0:00:01 --:--:-- 5929k
10:15:45 AM: [2/2]: https://y
10:15:45 AM: arnpkg.com/downloads/1.3.2/yarn-v1.3.2.tar.gz.asc --> /tmp/yarn.tar.gz.EU3hEijb6R.asc
10:15:45 AM: 
100    82  100    82    0     0   2987      0
10:15:45 AM: --:--:-- --:--:-- --:--:--  2987
10:15:45 AM: 
100    95  100    95    0     0   1697      0 --:--:-- --:--:-- --:--:--  1697
10:15:45 AM: 
100   633  100   633    0     0
10:15:45 AM:   3489      0 --:--:-- --:--:-- --:--:--  3489
10:15:45 AM: 1
10:15:45 AM: 00  102
10:15:45 AM: 7  100  1027    0     0   4665      0 --:--:-- --:--:-- --:--:--  4665
10:15:45 AM: > Verifying integrity...
10:15:45 AM: gpg: Signature made Thu 02 Nov 2017 04:44:10 PM UTC using RSA key ID FD2497F5
10:15:45 AM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
10:15:45 AM: gpg: Note: This key has expired!
10:15:45 AM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
10:15:45 AM:      Subkey fingerprint: 6A01 0C51 6600 6599 AA17  F081 46C2 130D FD24 97F5
10:15:45 AM: > GPG signature looks good
10:15:45 AM: > Extracting to ~/.yarn...
10:15:45 AM: > Adding to $PATH...
10:15:45 AM: > Successfully installed Yarn 1.3.2! Please open another terminal where the `yarn` command will now be available.
10:15:46 AM: Installing NPM modules using Yarn version 1.3.2
10:15:47 AM: yarn install v1.3.2
10:15:47 AM: (node:1277) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
10:15:47 AM: [1/4] Resolving packages...
10:15:48 AM: [2/4] Fetching packages...
10:16:34 AM: info fsevents@2.1.2: The platform "linux" is incompatible with this module.
10:16:34 AM: info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
10:16:34 AM: info fsevents@1.2.9: The platform "linux" is incompatible with this module.
10:16:34 AM: info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
10:16:34 AM: info fsevents@2.0.7: The platform "linux" is incompatible with this module.
10:16:34 AM: info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
10:16:34 AM: [3/4] Linking dependencies...
10:16:34 AM: warning "gatsby > @pmmmwh/react-refresh-webpack-plugin@0.2.0" has unmet peer dependency "sockjs-client@^1.4.0".
10:16:34 AM: warning "gatsby > react-hot-loader@4.12.20" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
10:16:34 AM: warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
10:16:34 AM: warning "gatsby > gatsby-cli > ink@2.7.1" has unmet peer dependency "@types/react@>=16.8.0".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-core > ajv-errors@1.0.1" has unmet peer dependency "ajv@>=5.0.0".
10:16:34 AM: warning "gatsby-plugin-netlify > webpack-assets-manifest@3.1.1" has unmet peer dependency "webpack@>=4.4.0".
10:16:34 AM: warning "gatsby-plugin-sass > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
10:16:34 AM: warning " > gatsby-remark-katex@3.2.1" has incorrect peer dependency "katex@^0.10.0".
10:16:34 AM: warning "gatsby-remark-katex > remark-math@1.0.6" has unmet peer dependency "remark-parse@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-backend-bitbucket@2.11.4" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-backend-bitbucket@2.11.4" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-backend-git-gateway@2.10.4" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-backend-git-gateway@2.10.4" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-backend-github@2.10.5" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-backend-github@2.10.5" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-backend-gitlab@2.8.4" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-backend-gitlab@2.8.4" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-backend-test@2.8.1" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-backend-test@2.8.1" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-backend-test@2.8.1" has unmet peer dependency "uuid@^3.3.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-core@2.26.0" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-core@2.26.0" has unmet peer dependency "moment@^2.24.0".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-core@2.26.0" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-lib-auth@2.2.8" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-lib-auth@2.2.8" has unmet peer dependency "uuid@^3.3.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-lib-util@2.9.3" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-ui-default@2.10.1" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-ui-default@2.10.1" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-boolean@2.3.0" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-boolean@2.3.0" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-code@1.1.4" has unmet peer dependency "codemirror@^5.46.0".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-code@1.1.4" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-date@2.5.0" has unmet peer dependency "moment@^2.24.0".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-date@2.5.0" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-file@2.6.4" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-file@2.6.4" has unmet peer dependency "uuid@^3.3.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-image@2.6.2" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-list@2.4.6" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-list@2.4.6" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-map@1.3.3" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-map@1.3.3" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-markdown@2.11.2" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-markdown@2.11.2" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-number@2.3.5" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-object@2.4.1" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-object@2.4.1" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-relation@2.6.0" has unmet peer dependency "lodash@^4.17.11".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-relation@2.6.0" has unmet peer dependency "netlify-cms-lib-widgets@^1.0.0".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-relation@2.6.0" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-relation@2.6.0" has unmet peer dependency "uuid@^3.3.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-select@2.5.1" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-string@2.2.3" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-text@2.3.0" has unmet peer dependency "prop-types@^15.7.2".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-core > react-frame-component@4.1.0" has unmet peer dependency "prop-types@^15.5.9".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-core > react-scroll-sync@0.6.0" has unmet peer dependency "prop-types@^15.x".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-core > react-sortable-hoc@1.9.1" has unmet peer dependency "prop-types@^15.5.7".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-ui-default > react-toggled@1.2.7" has unmet peer dependency "prop-types@>=15".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-code > react-codemirror2@6.0.0" has unmet peer dependency "codemirror@5.x".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-widget-date > react-datetime@2.16.3" has unmet peer dependency "moment@>=2.16.0".
10:16:34 AM: warning "netlify-cms-app > netlify-cms-core > redux-notifications > react-redux@4.4.10" has incorrect peer dependency "redux@^2.0.0 || ^3.0.0".
10:16:34 AM: warning "jest > @jest/core > jest-config > jest-environment-jsdom > jsdom@16.2.2" has unmet peer dependency "canvas@^2.5.0".
10:16:34 AM: warning "jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > ws@7.2.5" has unmet peer dependency "bufferutil@^4.0.1".
10:16:34 AM: warning "jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > ws@7.2.5" has unmet peer dependency "utf-8-validate@^5.0.2".
10:16:34 AM: warning "stylelint > @stylelint/postcss-css-in-js@0.37.1" has unmet peer dependency "postcss@>=7.0.0".
10:16:34 AM: warning "stylelint > @stylelint/postcss-markdown@0.36.1" has unmet peer dependency "postcss@>=7.0.0".
10:16:34 AM: warning "stylelint > postcss-html@0.36.0" has unmet peer dependency "postcss@>=5.0.0".
10:16:34 AM: warning "stylelint > postcss-syntax@0.36.2" has unmet peer dependency "postcss@>=5.0.0".
10:17:11 AM: [4/4] Building fresh packages...
10:17:27 AM: Done in 99.93s.
10:17:27 AM: NPM modules installed using Yarn
10:17:27 AM: (node:1462) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
10:17:27 AM: Started restoring cached go cache
10:17:27 AM: Finished restoring cached go cache
10:17:27 AM: go version go1.12 linux/amd64
10:17:27 AM: go version go1.12 linux/amd64
10:17:27 AM: Installing missing commands
10:17:27 AM: Verify run directory
10:17:27 AM: Executing user command: yarn build
10:17:28 AM: yarn run v1.3.2
10:17:28 AM: (node:1524) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
10:17:28 AM: $ yarn run clean && gatsby build
10:17:29 AM: (node:1546) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
10:17:29 AM: $ rimraf .cache public
10:17:33 AM: success open and validate gatsby-configs - 0.700s
10:17:34 AM: success load plugins - 1.924s
10:17:35 AM: success onPreInit - 0.024s
10:17:35 AM: success delete html and css files from previous builds - 0.038s
10:17:35 AM: success initialize cache - 0.036s
10:17:35 AM: success copy gatsby files - 0.104s
10:17:35 AM: success onPreBootstrap - 0.010s
10:17:35 AM: success createSchemaCustomization - 0.307s
10:17:36 AM: success source and transform nodes - 0.562s
10:17:36 AM: success building schema - 0.537s
10:17:36 AM: success createPages - 0.159s
10:17:36 AM: success createPagesStatefully - 0.094s
10:17:36 AM: success onPreExtractQueries - 0.001s
10:17:36 AM: success update schema - 0.041s
10:17:37 AM: success extract queries from components - 0.583s
10:17:37 AM: success write out requires - 0.009s
10:17:37 AM: success write out redirect data - 0.001s
10:17:37 AM: success Build manifest and related icons - 0.185s
10:17:37 AM: success onPostBootstrap - 0.187s
10:17:37 AM: ⠀
10:17:37 AM: info bootstrap finished - 8.370 s
10:17:37 AM: ⠀
10:18:13 AM: warning Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
10:18:13 AM: warning Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
10:18:13 AM: warning Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
10:18:13 AM: warning Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
10:18:13 AM: warning Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
10:18:13 AM: warning Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
10:18:15 AM: warning chunk styles [mini-css-extract-plugin]
10:18:15 AM: Conflicting order. Following module has been added:
10:18:15 AM:  * css ./node_modules/css-loader??ref--13-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-0-3!./src/components/Sidebar/Author/Author.module.scss
10:18:15 AM: despite it was not able to fulfill desired ordering with these modules:
10:18:15 AM:  * css ./node_modules/css-loader??ref--13-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-0-3!./src/components/Layout/Layout.module.scss
10:18:15 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-tags-list-template-js, component---src-templates-page-template-js, component---src-templates-tag-template-js, component---src-templates-category-template-js, component---src-templates-index-template-js
10:18:15 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-not-found-template-js, component---src-templates-categories-list-template-js
10:18:15 AM: warning chunk styles [mini-css-extract-plugin]
10:18:15 AM: Conflicting order. Following module has been added:
10:18:15 AM:  * css ./node_modules/css-loader??ref--13-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-0-3!./src/components/Icon/Icon.module.scss
10:18:15 AM: despite it was not able to fulfill desired ordering with these modules:
10:18:15 AM:  * css ./node_modules/css-loader??ref--13-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-0-3!./src/components/Layout/Layout.module.scss
10:18:15 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-tags-list-template-js, component---src-templates-page-template-js, component---src-templates-tag-template-js, component---src-templates-category-template-js, component---src-templates-index-template-js
10:18:15 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-not-found-template-js, component---src-templates-categories-list-template-js
10:18:15 AM: warning chunk styles [mini-css-extract-plugin]
10:18:15 AM: Conflicting order. Following module has been added:
10:18:15 AM:  * css ./node_modules/css-loader??ref--13-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-0-3!./src/components/Sidebar/Contacts/Contacts.module.scss
10:18:15 AM: despite it was not able to fulfill desired ordering with these modules:
10:18:15 AM:  * css ./node_modules/css-loader??ref--13-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-0-3!./src/components/Layout/Layout.module.scss
10:18:15 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-tags-list-template-js, component---src-templates-page-template-js, component---src-templates-tag-template-js, component---src-templates-category-template-js, component---src-templates-index-template-js
10:18:15 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-not-found-template-js, component---src-templates-categories-list-template-js
10:18:15 AM: warning chunk styles [mini-css-extract-plugin]
10:18:15 AM: Conflicting order. Following module has been added:
10:18:15 AM:  * css ./node_modules/css-loader??ref--13-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-0-3!./src/components/Sidebar/Copyright/Copyright.module.scss
10:18:15 AM: despite it was not able to fulfill desired ordering with these modules:
10:18:15 AM:  * css ./node_modules/css-loader??ref--13-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-0-3!./src/components/Layout/Layout.module.scss
10:18:15 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-tags-list-template-js, component---src-templates-page-template-js, component---src-templates-tag-template-js, component---src-templates-category-template-js, component---src-templates-index-template-js
10:18:15 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-not-found-template-js, component---src-templates-categories-list-template-js
10:18:15 AM: warning chunk styles [mini-css-extract-plugin]
10:18:15 AM: Conflicting order. Following module has been added:
10:18:15 AM:  * css ./node_modules/css-loader??ref--13-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-0-3!./src/components/Sidebar/Menu/Menu.module.scss
10:18:15 AM: despite it was not able to fulfill desired ordering with these modules:
10:18:15 AM:  * css ./node_modules/css-loader??ref--13-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-0-3!./src/components/Layout/Layout.module.scss
10:18:15 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-tags-list-template-js, component---src-templates-page-template-js, component---src-templates-tag-template-js, component---src-templates-category-template-js, component---src-templates-index-template-js
10:18:15 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-not-found-template-js, component---src-templates-categories-list-template-js
10:18:15 AM: warning chunk styles [mini-css-extract-plugin]
10:18:15 AM: Conflicting order. Following module has been added:
10:18:15 AM:  * css ./node_modules/css-loader??ref--13-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-0-3!./src/components/Sidebar/Sidebar.module.scss
10:18:15 AM: despite it was not able to fulfill desired ordering with these modules:
10:18:15 AM:  * css ./node_modules/css-loader??ref--13-oneOf-0-1!./node_modules/postcss-loader/src??postcss-4!./node_modules/sass-loader/dist/cjs.js??ref--13-oneOf-0-3!./src/components/Layout/Layout.module.scss
10:18:15 AM:    - couldn't fulfill desired order of chunk group(s) component---src-templates-tags-list-template-js, component---src-templates-page-template-js, component---src-templates-tag-template-js, component---src-templates-category-template-js, component---src-templates-index-template-js
10:18:15 AM:    - while fulfilling desired order of chunk group(s) component---src-templates-not-found-template-js, component---src-templates-categories-list-template-js
10:18:15 AM: success Building production JavaScript and CSS bundles - 37.749s
10:18:15 AM: success Rewriting compilation hashes - 0.001s
10:18:16 AM: success run queries - 38.701s - 31/31 0.80/s
10:18:21 AM: success Building static HTML for pages - 5.412s - 28/28 5.17/s
10:18:22 AM: info Generated public/sw.js, which will precache 10 files, totaling 449411 bytes.
10:18:22 AM: The following pages will be precached:
10:18:22 AM: /offline-plugin-app-shell-fallback/index.html
10:18:22 AM: 1 SVGs minified, reducing the total size from 1979 bytes to 1386 bytes, a reduction of 30.0%!
10:18:22 AM: success onPostBuild - 0.585s
10:18:22 AM: info Done building in 53.112 sec
10:18:22 AM: Done in 54.32s.
10:18:22 AM: Skipping functions preparation step: no functions directory set
10:18:22 AM: Caching artifacts
10:18:22 AM: Started saving node modules
10:18:22 AM: Finished saving node modules
10:18:22 AM: Started saving build plugins
10:18:22 AM: Finished saving build plugins
10:18:22 AM: Started saving yarn cache
10:18:22 AM: Finished saving yarn cache
10:18:22 AM: Started saving pip cache
10:18:30 AM: Finished saving pip cache
10:18:30 AM: Started saving emacs cask dependencies
10:18:30 AM: Finished saving emacs cask dependencies
10:18:30 AM: Started saving maven dependencies
10:18:30 AM: Finished saving maven dependencies
10:18:30 AM: Started saving boot dependencies
10:18:30 AM: Finished saving boot dependencies
10:18:30 AM: Started saving go dependencies
10:18:30 AM: Finished saving go dependencies
10:18:33 AM: Build script success
10:18:33 AM: Starting to deploy site from 'public'
10:18:33 AM: Creating deploy tree 
10:18:33 AM: Creating deploy upload records
10:18:34 AM: 1 new files to upload
10:18:34 AM: 0 new functions to upload
10:18:34 AM: Pushing to repository git@github.com:[account]/[repo]
10:18:34 AM: Starting post processing
10:18:35 AM: Post processing done
10:18:35 AM: Site is live
10:18:40 AM: Error pushing to remote repository at git@github.com:[account]/[repo]
10:18:40 AM: Finished processing build request in 3m7.036291404s

**To Reproduce**
1. Go to 'https://github.com/alxshelepenok/gatsby-starter-lumen'
2. Click on 'Deploy with Netlify' Button on 'Deploy with Netlify' Section
3. Follow the steps, by connecting to your GitHub account, give a repo name
4. You can see your site is live but in the deploy logs you will see that the code is not pushed to GitHub and your newly created repo should have the clone of the code.

**Expected behavior**
A copy of the code should be pushed to GitHub repo that is created

**Desktop (please complete the following information):**
 - chrome

**Comment by Subhojit1992** [comment]
I face the same issue.
