### ISSUE TITLE
Replace flow by typescript if it's possible.

### ISSUE THREAD

**Issue by marekdano** [alxshelepenok/gatsby-starter-lumen#679]
I use the VS Code and it's frustrated to see the types are highlighted there and the error of `Type annotations can only be used in TypeScript files.` is displayed beside them.

It'll be really great if `flow` is replaced by `typescript` across all codebase. I think more people will benefit from it.

**Comment by ignlg** [comment]
I totally support this change.

@marekdano Just wanted to comment a fix for the VSCode issue:
- Go to Extensions
- Search `@builtin typescript`
- Select _TypeScript and JavaScript Language Features_
- Disable it for the workspace: `Disable (Workspace)`

**Comment by marekdano** [comment]
@ignlg thanks for the fix. I can confirm it solved my issue in VSCode. 

Still think it would be better to have typescript instead of flow types in this template.

**Comment by eladc1** [comment]
I'm doing this in my personal project, do you want me to try to separate this change, so I'll can do PR when I'm done?

**Comment by vitaliitylyk** [comment]
@eladc1 That would be great if you do that. I will be very helpful for many starter users (plus I hope @alxshelepenok will accept it)
