### ISSUE TITLE
Navigation between pages

### ISSUE THREAD

**Issue by arjunmayilvaganan** [alxshelepenok/gatsby-starter-lumen#68]
A Small thought.

I wanted to express that when navigating between - _Articles_, _About me_ & _Contact me_ in mobile phones of medium sized screens, it is not easy for the visitor to realise that the selected section has been rendered below, upon selection, because the page is pretty much still and the only indication is the selected section being highlighted, i.e., it appears like in the picture below:

![pages-navigation](https://user-images.githubusercontent.com/6371303/38630393-6debd62e-3dd4-11e8-9aa6-7c7cf89d9386.png)

The visitor could miss scrolling to find out that the selected section has actually been rendered below.

Would auto-scroll to section title help?

**Comment by alxshelepenok** [comment]
Fixed in https://github.com/alxshelepenok/gatsby-starter-lumen/commit/1ac51111f704d71de50c75eaee6990aeabb3d98b
