### ISSUE TITLE
Create a dropdown for tags and categories 

### ISSUE THREAD

**Issue by sumanstats** [alxshelepenok/gatsby-starter-lumen#687]
**Is your feature request related to a problem? Please describe.**
No. I want some customisation while using this theme.

**Describe the solution you'd like**
I want to put two dropdowns `Tags` and `Categories` in upper right corner similar to the figure shown below. And for *each post*, can I customise to include both tags and category **or** to remove them altogether?

**Describe alternatives you've considered**
I searched for options to do it but no avail.

**Additional context**
<img width="873" alt="Capture" src="https://user-images.githubusercontent.com/8075886/84044760-b1839c80-a9c7-11ea-92d1-51efdaae19dd.PNG">

**Comment by mohamedabusrea** [comment]
You can have a look at the src/hooks folder. it has useful hooks like use-tags-list.js which gives you a list of all tags and use-categories-list.js which gives you a list of all categories and you can add them in the dropdown list as you wish 🤓
