### ISSUE TITLE
Is there a way to extend this to dark theme?

### ISSUE THREAD

**Issue by ShahAnuj2610** [alxshelepenok/gatsby-starter-lumen#688]
**Is your feature request related to a problem? Please describe.**
- I tried changing color scheme by changing `color` variables inside `_variables.css` file `color-base`, `color-primary` and `color-secondary` to dark color schemes, but the UI looks quite bad

**Describe the solution you'd like**
- changing these three colors to dark color scheme, should enable website in dark mode

**Alternatives**
- I tried searching some articles on Gatsby theme, but didn't find anything helpful that can be applied here. 
- Even if there's no immediate sol'n, is there a quick hack or a blog that can help me out?

**Comment by payamazadi** [comment]
In Layout.module.scss, I added:
```
body {
    background-color: #000;
}
```

And in variables, I used:
```
$color-base: #888;
$color-primary: #6666ca;
$color-secondary: #746e6b;
```

Not amazing, but a decent start. Does this help you?

**Comment by joaommartins** [comment]
I did it on my own blog based on Lumen and published it as a post, you can find the guide [here](https://joaommartins.github.io/posts/gatsby-lumen-and-dark-mode).

Feel free to ask if you have any questions.
