### ISSUE TITLE
Disqus url undefined

### ISSUE THREAD

**Issue by doakheggeness** [alxshelepenok/gatsby-starter-lumen#69]
How do I activate Disqus. The ``` props.url ```  in ``` <DisqiusThread/> ``` comes back with the ``` https://url/undefined  ``` when on a post.  The 'path' for the post is undefined.

Thanks
![disqus](https://user-images.githubusercontent.com/1179369/39961688-8d62a364-55f0-11e8-9f55-23a0b679c5a2.jpg)

**Comment by dalareo** [comment]
I think this issue is also related:
At line 27 of disqus.jsx I get an error as postNode.fields is undefined

````
const url = siteMetadata.url + postNode.fields.slug;

**Comment by arturoleon** [comment]
I opened a pull request (#75) to fix this problem.
