### ISSUE TITLE
How to use custom favicon rather than photo.jpg in static folder?

### ISSUE THREAD

**Issue by asd617140123** [alxshelepenok/gatsby-starter-lumen#706]
**Describe the bug**

Add custom favicon

**Comment by Jarmos-san** [comment]
You can change the default the image under `./static/`, so change the default `./static/photo.jpg` with your own image of choice at `./static/<IMAGE-OF-YOUR-CHOICE>`.

Also, note that doing so will also change the default image on the sidebar.

Perform a hard refresh with `ctr+R` in the browser as the favicon doesn't change sometimes.

**Comment by alxshelepenok** [comment]
Thank you for your feedback. The starter has been updated to the new version and the bug has probably been fixed.
