### ISSUE TITLE
gatsby-remark-images is not working

### ISSUE THREAD

**Issue by Mandaline** [alxshelepenok/gatsby-starter-lumen#710]
**Describe the bug**
gatsby-remark-images is not processing images

**To Reproduce**
1. Install and deploy a new Gatsby Lumen starter
2. Inspect an image in a post or page

**Expected behavior**
In the [Lumen demo](https://lumen.netlify.app/), this feature seems to be working perfectly

**Screenshots**
In a fresh install, I'm seeing normal src tags instead of responsive wrappers: 
<img width="735" alt="Screen Shot 2020-07-18 at 8 01 10 PM" src="https://user-images.githubusercontent.com/33697083/87863465-7f078080-c931-11ea-98c3-bffef7be0c17.png">

**Additional context**
I really hope to find a solution since this starter has been great to work with!

**Comment by hypeahead** [comment]
@Mandaline "gatsby-remark-relative-images" might be the issue, try running version 0.2.3 instead and see if that fixes the issue. Some further details here:
https://github.com/danielmahon/gatsby-remark-relative-images/issues/31

**Comment by Mandaline** [comment]
Perfect! Now it's working as expected. Thank you!
