### ISSUE TITLE
How do you update the sidebar contents?

### ISSUE THREAD

**Issue by mohammedasker** [alxshelepenok/gatsby-starter-lumen#711]
This may be a simple question, but how do you update the sidebar contents? At the moment, I cannot see the changed contents until I either restarted the Gatsby server `Gatsby develop` or push the changes to remote repo and view from netlify site.

**Comment by ibraheemdev** [comment]
The sidebar gets its data from a static query of the config.js file. The server must be restarted to see the changes due to the nature of the `useStaticQuery` method; the file is read only once at the beginning.

**Comment by mohammedasker** [comment]
I see. So in other words, it is unavoidable to restart the server every time I make changes to `gatsby-config.js` file. Thanks for the explanation, @ibraheemdev.
