### ISSUE TITLE
Add a previous/next on blogposts

### ISSUE THREAD

**Issue by StephanWeinhold** [alxshelepenok/gatsby-starter-lumen#74]
I'm struggling with adding a prev- and a next-link to my blogposts (like in the [default blog starter](https://github.com/gatsbyjs/gatsby/blob/master/www/gatsby-node.js#L166-L180)). Has anyone achieved this? Or an idea how I can implement this?

**Comment by alxshelepenok** [comment]
@StephanWeinhold, i added this in the new version (https://github.com/alxshelepenok/gatsby-starter-lumen/tree/master/gatsby/pagination)

**Comment by StephanWeinhold** [comment]
Thanks a lot!
