### ISSUE TITLE
problem with gatsby-remark-relative-images 2.0.2

### ISSUE THREAD

**Issue by OlaWod** [alxshelepenok/gatsby-starter-lumen#741]
**Describe the bug**
Today I forked this repo and without modifying anything I deployed to netlify and got this error:

> 5:31:36 PM: error "gatsby-remark-relative-images" threw an error while running the onCreateNode lifecycle:
> 5:31:36 PM: No matching file found for src "/media/image-2.jpg" in static folder "static". Please check static folder name and that file exists at "static/media/image-2.jpg". This error will probably cause a "GraphQLDocumentError" later in build. All converted field paths MUST resolve to a matching file in the "static" folder.

Then I downgraded gatsby-remark-relative-images to 0.2.3 and deployed again and succeeded.

**Comment by alxshelepenok** [comment]
Fixed in https://github.com/alxshelepenok/gatsby-starter-lumen/pull/755
