### ISSUE TITLE
Using template without CMS

### ISSUE THREAD

**Issue by IIPatternII** [alxshelepenok/gatsby-starter-lumen#750]
This is just a question.

Is it ok to use this template without the CMS and just creating files on the `content/post` folder? Is there a technical reason why not to do it? like a decrease in performance?

Thank you for your time!

**Comment by vinnymac** [comment]
This is fine. The template was originally not using a CMS at all. I’ve never used the CMS service and have been using this template since the project started.

I’ve opened up #855 to make it easier to start local development, if that is what you’re interested in.
