### ISSUE TITLE
Field "socialImage" must not have a selection since type "String" has no subfields.

### ISSUE THREAD

**Issue by sahirmpatel** [alxshelepenok/gatsby-starter-lumen#761]
**Describe the bug**
There was an error in your GraphQL query: 
Field "socialImage" must not have a selection since type "String" has no subfields.

**To Reproduce**
After running gatsby develop this error occurs.

` ERROR #85922  GRAPHQL

There was an error in your GraphQL query:

Field "socialImage" must not have a selection since type "String" has no subfields.

This can happen if you e.g. accidentally added { } to the field "socialImage". If you didn't expect "socialImage" to be of type "String" make sure that your input source and/or plugin is correct.

File: src\templates\page-template.js:53:21

`

**Additional context**
It was working fine before https://github.com/alxshelepenok/gatsby-starter-lumen/commit/5c7fa1046018c6ceb1ce11fa70c67486874b9d6a

**Comment by OlaWod** [comment]
I wrote `socialImage: ""` in a markdown file without pictures and got this error in Netlify too.

Here's how I solve this problem:
- Step 1: Write  `socialImage: `  instead or just delete it in the markdown file.
After this it'll get the following error in Netlify 👇.
```bash
11:10:32 PM: failed Building static HTML for pages - 5.935s
11:10:32 PM: error Building static HTML failed for path "/pages/contacts/"
11:10:32 PM: 
11:10:32 PM:   20 |   const { title: pageTitle, description: pageDescription, socialImage } = frontmatter;
11:10:32 PM:   21 |   const metaDescription = pageDescription !== null ? pageDescription : siteSubtitle;
11:10:32 PM: > 22 |   const socialImageUrl = typeof socialImage !== 'undefined' ? socialImage['publicURL'] : undefined;
11:10:32 PM:      |                                                                           ^
11:10:32 PM:   23 | 
11:10:32 PM:   24 |   return (
11:10:32 PM:   25 |     <Layout title={`${pageTitle} - ${siteTitle}`} description={metaDescription} socialImage={socialImageUrl} >
11:10:32 PM: 
11:10:32 PM:   WebpackError: TypeError: Cannot read property 'publicURL' of null
11:10:32 PM:   
11:10:32 PM:   - page-template.js:22 
11:10:32 PM:     src/templates/page-template.js:22:75
```
- Step 2: Change  `const socialImageUrl = typeof socialImage !== 'undefined' ? socialImage['publicURL'] : undefined;`  to  `const socialImageUrl = socialImage === null || typeof socialImage === 'undefined' ? undefined : socialImage['publicURL'];`  in page-template.js and post-template.js.
- Now it works well in Netlify and Travis.

**Comment by rouisoufiane** [comment]
> 
> 
> I wrote `socialImage: ""` in a markdown file without pictures and got this error in Netlify too.
> 
> Here's how I solve this problem:
> 
>     * Step 1: Write  `socialImage: `  instead or just delete it in the markdown file.
>       After this it'll get the following error in Netlify 👇.
> 
> 
> ```shell
> 11:10:32 PM: failed Building static HTML for pages - 5.935s
> 11:10:32 PM: error Building static HTML failed for path "/pages/contacts/"
> 11:10:32 PM: 
> 11:10:32 PM:   20 |   const { title: pageTitle, description: pageDescription, socialImage } = frontmatter;
> 11:10:32 PM:   21 |   const metaDescription = pageDescription !== null ? pageDescription : siteSubtitle;
> 11:10:32 PM: > 22 |   const socialImageUrl = typeof socialImage !== 'undefined' ? socialImage['publicURL'] : undefined;
> 11:10:32 PM:      |                                                                           ^
> 11:10:32 PM:   23 | 
> 11:10:32 PM:   24 |   return (
> 11:10:32 PM:   25 |     <Layout title={`${pageTitle} - ${siteTitle}`} description={metaDescription} socialImage={socialImageUrl} >
> 11:10:32 PM: 
> 11:10:32 PM:   WebpackError: TypeError: Cannot read property 'publicURL' of null
> 11:10:32 PM:   
> 11:10:32 PM:   - page-template.js:22 
> 11:10:32 PM:     src/templates/page-template.js:22:75
> ```
> 
>     * Step 2: Change  `const socialImageUrl = typeof socialImage !== 'undefined' ? socialImage['publicURL'] : undefined;`  to  `const socialImageUrl = socialImage === null || typeof socialImage === 'undefined' ? undefined : socialImage['publicURL'];`  in page-template.js and post-template.js.
> 
>     * Now it works well in Netlify and Travis.

Thanks @OlaWod. I've tried your solution, unfortunately, it did not work for me (local).

**Comment by BenAckland** [comment]
I also had this issue locally on a windows machine. The build still ran fine in my github action though.

Installing this plugin resolved it for me:
https://www.gatsbyjs.com/plugins/gatsby-plugin-netlify-cms-paths/

**Comment by lucalves** [comment]
I am also having the same problem, and none of the previous solutions worked.

**Comment by hughsername** [comment]
### Plugin Order Matters

Hey everyone, if the netlify-cms-paths plugin isn't working for you on Windows, but works on Netlify/Github Actions, then you need to make sure you've listed the reference to gatsby-plugin-netlify-cms-paths BEFORE gatsby-transformer-remark inside your Gatsby config.

**Comment by tranlehaiquan** [comment]
@hughsername work well for me,

- Install `gatsby-plugin-netlify-cms-paths`
- add `gatsby-plugin-netlify-cms-paths` BEFORE gatsby-transformer-remark

**Comment by sureshHARDIYA** [comment]
It seems this is related to `nodeJS` version. I had `node version = v14.15.0` and I got this error. Then I changed to the latest version, `v15.0.1` and the error resolves. 

Disclaimer: I did not check the PR or recent changes done in the codebase. I just noticed this error on my localhost and changed to current version of node, and my personal site is running fine.

**Comment by justinphilpott** [comment]
> It seems this is related to `nodeJS` version. I had `node version = v14.15.0` and I got this error. Then I changed to the latest version, `v15.0.1` and the error resolves.
> 
> Disclaimer: I did not check the PR or recent changes done in the codebase. I just noticed this error on my localhost and changed to current version of node, and my personal site is running fine.

Running on node 15.9.0 and error still shows

**Comment by marcomelilli** [comment]
I solved by adding at least one page/post with the metadata socialImage not empty.
You can add  for example `socialImage: { publicURL: ''}` in a .md file

**Comment by chiki3839** [comment]
@hughsername and @tranlehaiquan comment teach me  solutions.
1. Install gatsby-plugin-netlify-cms-paths
`yarn add gatsby-plugin-netlify-cms-paths`

2. Add  a setting before gatsby-transformer-remark to gatsby-config.js (at "plugins:").
```
    // Including in your Gatsby plugins will transform any paths in your frontmatter
    `gatsby-plugin-netlify-cms-paths`,

    // Including in your Remark plugins will transform any paths in your markdown body
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          `gatsby-plugin-netlify-cms-paths`,
        ],
      },
    },

```
https://www.gatsbyjs.com/plugins/gatsby-plugin-netlify-cms-paths/
