### ISSUE TITLE
Error in field "socialImage"

### ISSUE THREAD

**Issue by lucalves** [alxshelepenok/gatsby-starter-lumen#777]
It's similar to #761, but not the same.

## Description

When I run the command `gatsby develop`, i have the following error:

There was an error in your GraphQL query:

Field "socialImage" must not have a selection since type "String" has no subfields.

This can happen if you e.g. accidentally added { } to the field "socialImage". If you didn't expect "socialImage" to be of type "String" make sure that your input source and/or plugin is correct.

File: blog/src/templates/page-template.js

There was an error in your GraphQL query:

Field "socialImage" must not have a selection since type "String" has no subfields.

This can happen if you e.g. accidentally added { } to the field "socialImage". If you didn't expect "socialImage" to be of type "String" make sure that your input source and/or plugin is correct.

File: blog/src/templates/post-template.js

**Comment by germanbobadilla** [comment]
Same here. And the code happens to be marked as though it has a lot of errors. And it looks like the code it's written in TS, although the file ext are in js. Why so many errors without even touching the code?

**Comment by 7ukas** [comment]
same to me. Do you resolve it?

**Comment by khjeon5328** [comment]
Is there any solution about this matter? I have same error

**Comment by lucalves** [comment]
At the moment, no. @khjeon5328

**Comment by Everspace** [comment]
@germanbobadilla That is because the codebase uses flow instead of typescript.

**Comment by hughsername** [comment]
I had this same error today. Posting over here in case you didn't see it on #761 - if you're on Windows, this is because the path is not resolving for the Netlify CMS. You can add a Gatsby plugin (gatsby-plugin-netlify-cms-paths) to your gatsby-config and it will correct this, but **only** if you add it before `gatsby-transformer-remark`.
