### ISSUE TITLE
Recommended path for updating?

### ISSUE THREAD

**Issue by mikebell** [alxshelepenok/gatsby-starter-lumen#788]
What's the best way to go about updating an existing site running this starter theme?

Is it as simple as replacing all the files with the new release?

**Comment by yujinyuz** [comment]
I also want to know what's the recommended way. Currently what I did was

`git pull origin master --allow-unrelated-histories`

and resolved the conflicts from there (I haven't changed much on my end so it I had no problems with resolving the conflicts)
