### ISSUE TITLE
Bumping autoprefixer to v10 causes error in webpack

### ISSUE THREAD

**Issue by gabewomble** [alxshelepenok/gatsby-starter-lumen#799]
**Describe the bug**
Autoprefix v10 depends on PostCSS 8, and as a result the bump to v10 has caused webpack to error

**To Reproduce**
1. pull master
2. `yarn && yarn develop`

**Expected behavior**
Development build should compile

**Actual behavior**
Webpack Error

```sh
ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

PostCSS plugin autoprefixer requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
```

**Notes**
I fixed this locally by using autoprefixer@9.0.0, looks like the best solution is to revert #768

**Comment by theapplegates** [comment]
I was just going to report this. 
Found a solution [here](https://stackoverflow.com/questions/63944242/migrating-postcss-loader-from-3-0-0-to-4-0-2-results-in-error-object-object-i) on Stackoverflow.

Just change "autoprefixer": "9.7.0", and it works fine, for me anyway.

**Comment by gabewomble** [comment]
@theapplegates I found that as well! I mentioned at the bottom of the issue post that this should be fixable by reverting the PR #768 (created by a dependency bot)

**Comment by alxshelepenok** [comment]
Revert "chore(deps): update dependency autoprefixer to v10" #801
