### ISSUE TITLE
Adding Additional Sidebar Logos

### ISSUE THREAD

**Issue by reggie3** [alxshelepenok/gatsby-starter-lumen#80]
Can anyone provide details on adding additional logos for use in the Links component which is a child of the Sidebar component?  

I can see that the links are assigned classes that exist in multiple Fontello related files.   For example, a search for the `icon-github` class showed that it existed in five CSS and one HTML file.

![image](https://user-images.githubusercontent.com/7347192/50308426-2c21ca80-0469-11e9-9257-8ba77e683263.png)

Is there a way to add another logo?  I am trying to add one for Medium.com
![image](https://user-images.githubusercontent.com/7347192/50308496-6a1eee80-0469-11e9-830d-1ffd85d119c7.png)

**Comment by maaz93** [comment]
I did this a few days back. I needed to reduce the list of icons. Here are the steps

1. Import the existing [config.json](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/assets/fonts/fontello-771c82e0/config.json) at http://fontello.com/
<img width="263" alt="screenshot 2018-12-27 at 9 55 06 pm" src="https://user-images.githubusercontent.com/6594255/50486954-51db4080-0a22-11e9-829d-ea954cda0ff0.png">
1. Make your changes, by selecting/deselecting the icons
1. Download the new font and use it

**Comment by maaz93** [comment]
@alxshelepenok Should I send a PR with this content to the readme?

**Comment by alxshelepenok** [comment]
@maazadeeb of course, but I think it is best to add a new markdown-file with tutorials for this purpose.

It might look like this:
```
+ [Tutorials](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/TUTORIALS.md)
    + [Adding additional sidebar icons](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/TUTORIALS.md#adding-additional-sidebar-icons)
```
![img](https://i.imgur.com/HSsTJfR.png)
