### ISSUE TITLE
Creating all posts page prior to tags and categories causes issue

### ISSUE THREAD

**Issue by BinaryJim** [alxshelepenok/gatsby-starter-lumen#803]
Hi

I’m referencing your starter to build my own Gatsby prototype. I noticed in gatsby node you call the function to create all posts pages (your blog root), after calling the functions to build categories and tags pages. 

I’ve noticed if I build my all posts page first (prior to categories and tags), the categories and tags pages do not get built. However, this is not the case If I build the all posts page after building the categories and tags pages. 

I just wanted to check if this was a similar issue for you and perhaps the reason why you build your all posts page after building categories and tags pages?

https://github.com/alxshelepenok/gatsby-starter-lumen/blob/eefc951085aad338f53d220432eac3c377cbfae9/gatsby/create-pages.js#L71

Thanks

**Comment by payamazadi** [comment]
I moved line 72 (createPostsPages) to happen first, and everything seemed to work fine for me. Is that what you meant? What are you experiencing?
