### ISSUE TITLE
Invalid plugin options for "gatsby-plugin-sass"

### ISSUE THREAD

**Issue by RonakR** [alxshelepenok/gatsby-starter-lumen#815]
**Describe the bug**
My current Lumen install shows this error on `yarn develop` with all updated packages. 
I did a fresh install of Lumen and the error still happens. 
When running `yarn develop` the following error occurs:
```
error Invalid plugin options for "gatsby-plugin-sass":

- "postCssPlugins[0]" must be of type object
- "postCssPlugins[1]" must be of type object
- "postCssPlugins[2]" must be of type object
```

**To Reproduce**
1. Create a new Lumen project: `gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumenn`
2. Run `yarn develop`

**Expected behavior**
`yarn develop` set up and serves gatsby locally

**Screenshots**
![image](https://user-images.githubusercontent.com/3664474/98198070-2535c100-1ef6-11eb-8dc4-752304509a3e.png)

**Desktop (please complete the following information):**
 - MacOS

**Comment by eladc1** [comment]
Duplicate. close and use https://github.com/alxshelepenok/gatsby-starter-lumen/issues/816
