### ISSUE TITLE
Invalid plugin options for "gatsby-plugin-sass"

### ISSUE THREAD

**Issue by RonakR** [alxshelepenok/gatsby-starter-lumen#816]
**Describe the bug**
When running `yarn develop` in a Lumen project, the following error occurs:
```
error Invalid plugin options for "gatsby-plugin-sass":

- "postCssPlugins[0]" must be of type object
- "postCssPlugins[1]" must be of type object
- "postCssPlugins[2]" must be of type object
```
This happens in my current Lumen project and with a fresh install. 

**To Reproduce**
1. Create a new Lumen project: `gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumenn`
2. Run `yarn develop`
3. See error

**Expected behavior**
`yarn develop` sets up and serves the gatsby website locally

**Screenshots**
![image](https://user-images.githubusercontent.com/3664474/98198441-fbc96500-1ef6-11eb-85d1-ef27984ca664.png)

**Desktop (please complete the following information):**
 - MacOS Catalina

**Comment by eladc1** [comment]
That a bug with gatsby-plugin-sass itself, they wrote a fix, wait for them to merge this fix.
look here:
https://github.com/gatsbyjs/gatsby/pull/27829

for now you can downgrade to gatsby-plugin-sass@2.3.22

**Comment by RonakR** [comment]
Awesome, that did the trick. 
Thanks for the prompt response!
