### ISSUE TITLE
 no such file or directory, open 'C:\Users\me\Documents\DEV\allmydev\.cache\json\[slug].json'

### ISSUE THREAD

**Issue by Triskae** [alxshelepenok/gatsby-starter-lumen#828]
**Describe the bug**
Hello, I'm on Windows, and when a `gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumen`, `cd blog` and `gatsby develop`, it starts to build but at the end I have this error :

`
success Building development bundle - 12.999s
error ENOENT: no such file or directory, open 'C:\Users\me\Documents\DEV\allmydev\.cache\json\_pages_about_.json'
`

**To Reproduce**
On windows 10

1: `gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumen`
2: `cd blog`
3: `gatsby develop`

**Expected behavior**
The project starts right, but not (I tried on my Macbook and it works fine)

**Screenshots**
[Screenshot](https://ibb.co/SyKqW0G)

**Desktop (please complete the following information):**
 - OS: Windows 10,
 - Browser: Brave
 - Version 19041.630

**Additional context**
Works fine on macos, but not on my windows.

Thanks a lot guys !

**EDIT**: The version 3.0.5 is working fine, the nearest branch 'bugfix/#741' is not working though ... It's something between this two points thats seems to break something ...

**EDIT 2**: It seems that the problem is generated by  this commit :
The head commit is working and the commit juste above not. The above commit is the installation of 
[Screenshot](https://hostpic.xyz/image/screen.R3rQy)
May be related to this ? [Github issue](https://github.com/gatsbyjs/gatsby/issues/5991#issuecomment-398692662)

**Comment by diogoverde** [comment]
Had the same issue, looked into the socialImage problem and could not yet find a solution. Removing the socialImage from both the Graphql queries solved the initial problem

**Comment by Triskae** [comment]
> Had the same issue, looked into the socialImage problem and could not yet find a solution. Removing the socialImage from both the Graphql queries solved the initial problem. Even though this is not a solution, just wanted to provide something to be able to run the template while a solution is produced 😄

Thanks a lot, I will give it a try 😄

Really strange, working on macos but not in windows 😄

**Comment by eari100** [comment]
> Had the same issue, looked into the socialImage problem and could not yet find a solution. Removing the socialImage from both the Graphql queries solved the initial problem. Even though this is not a solution, just wanted to provide something to be able to run the template while a solution is produced 😄

Thank you very much.
It works fine by deleting the socialImage node in the page-template.js and post-template.js files.
