### ISSUE TITLE
https://.disqus.com/embed.js net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by yeshtml5** [alxshelepenok/gatsby-starter-lumen#83]
![image](https://user-images.githubusercontent.com/20413597/51588505-c0c78e80-1f27-11e9-8ff8-828f67c3ab53.png)

IndexPage -> Article something into 
Error..   

```
https://.disqus.com/embed.js net::ERR_NAME_NOT_RESOLVED
```

**Comment by alxshelepenok** [comment]
Perhaps this is due to the fact that an empty shortname is passed to the reactDisqusComments component.
[/src/components/Post/Comments/Comments.js#L12](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/src/components/Post/Comments/Comments.js#L12)
Do you want to create PR?

**Comment by alxshelepenok** [comment]
Fixed in https://github.com/alxshelepenok/gatsby-starter-lumen/commit/dd960574945c83aa03db8000ccf451816ec07752
