### ISSUE TITLE
Deploy to Netlify doesnt copy the files to the new repository

### ISSUE THREAD

**Issue by laxmena** [alxshelepenok/gatsby-starter-lumen#839]
**Describe the bug**
Deploy to Netlify, creates a new repository but doesnt copy the contents from this repo to the newly created repository. The newly created repo is empty.

**To Reproduce**
1. Go to https://app.netlify.com/start/deploy?repository=https://github.com/alxshelepenok/gatsby-starter-lumen
2. After connecting to GitHub and providing a new name for the repository, Click on "Save & Deploy".
3. Wait till the site is deployed.
4. Go check GitHub, the repository is empty

**Expected behavior**
Contents of the gatsby-starter-lumen should be copied to the new repository.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Comment by dimchanske** [comment]
Confirm that's what happening for me too.
Was thinking i'm doing something wrong but then found this issue.

**Comment by dimchanske** [comment]
Seems like Github Actions are somehow preventing Netlify to push into the forked repo
Related issue: https://github.com/stackrole/gatsby-starter-foundation/issues/2

**Comment by tranlehaiquan** [comment]
Confirmed,
I have to Fork the project and setup Netlify from my own repo.
