### ISSUE TITLE
Dark Mode with macOS Mojave

### ISSUE THREAD

**Issue by alxshelepenok** [alxshelepenok/gatsby-starter-lumen#84]
It is necessary to implement the functionality of switching between dark and light theme on macOS Mojave
[Paul Miller - Using dark mode in CSS with MacOS Mojave](https://paulmillr.com/posts/using-dark-mode-in-css/)

**Comment by astonyao** [comment]
Is this feature still going to be implemented?

**Comment by astonyao** [comment]
any updates on this one? I might start on it if nobody is working on it.

**Comment by vzhou842** [comment]
@astonyao nobody is working on this AFAIK, you're welcome to take the lead on this!

**Comment by alxshelepenok** [comment]
@astonyao Hi, this is not the time for this. I will open the Issue again later.

**Comment by joevo2** [comment]
any progress on this?
