### ISSUE TITLE
Fresh install React dependency resolve problem

### ISSUE THREAD

**Issue by abbaselmas** [alxshelepenok/gatsby-starter-lumen#846]
Installed the latest nodejs
Installed gatsby-cli

gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumen

result is below:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: gatsby-starter-lumen@3.0.7
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.4.2" from gatsby@2.29.1
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^2.28.2" from the root project
npm ERR!   peer gatsby@"*" from @sentry/gatsby@5.29.2
npm ERR!   node_modules/@sentry/gatsby
npm ERR!     @sentry/gatsby@"^5.29.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

I am no expert in node or gatsby but react has dependency problems i think.

**Comment by timkettering** [comment]
same thing!

**Comment by daaanny90** [comment]
@abbaselmas Have you closed the issue because you have solved it? Can you provide a solution? I have the same problem.

**Comment by abbaselmas** [comment]
> @abbaselmas Have you closed the issue because you have solved it? Can you provide a solution? I have the same problem.

No I couldn't find a solution netiher resolve this issue. There are issues stating that order of the plugins cause this problem.
I am not familiar with gatsby or npm. I gave up on gatsby and working on nextjs and vercel combination.
Btw deploy to netlify button works with no error. I think thats why they dont look at this kind of issues at all.

**Comment by daaanny90** [comment]
I found the solution. Going into the folder and using `yarn install` instead of `npm install` will solve the dependency problems 👍

**Comment by abbaselmas** [comment]
resolved with #856
