### ISSUE TITLE
Page load anchor point on mobile

### ISSUE THREAD

**Issue by disidrosi** [alxshelepenok/gatsby-starter-lumen#868]
**Problem**: The mobile version loads the website at the beginning of the page content, rather than the beginning of the website navigation.

**How to replicate**: To understand what I mean, open [the starter demo](https://lumen.netlify.app/). This will open on the blog posts page, which on a computer screen will have the navigation bar on the left and the page content on the right. Now resize the browser by dragging the window towards the left or right, until it reaches the minimum dimensions. The navigation bar now moves to the top, and the blog posts move to the bottom. If you try to reload the page, it will always bring you at the beginning of "posts". If you want to see the navigation, you have to scroll all the way up. This works the same on any page, so I believe there is a redirection set somewhere to always set the focus on the page content first.

**Request**: Is there a way to change this? I'd like to have the page load from the very start, i.e. from the beginning of navigation, but I don't seem to be able to find out how.

Thanks a lot to anyone for the help. :)

**Comment by mocon** [comment]
I am also wondering how to turn this off. Thanks!
