### ISSUE TITLE
failed Building development bundle , error in the first gatsby develop command 

### ISSUE THREAD

**Issue by juuni26** [alxshelepenok/gatsby-starter-lumen#877]
I just follow the quick start. after creating new site fresh i tried to `gatsby develop`  for the first time.  then error is showed below :

1. There was an error in your GraphQL query:

      Field "socialImage" must not have a selection since type "String" has no
subfields.

it's already solved by #761 following the answer there from the folks.

2. then after fixing the error, comes another error which is "Generating development JavaScript bundle failed"

ERROR #98123  WEBPACK

Generating development JavaScript bundle failed , it's shown in many files. what should i do ?  it's said error by typescript , i never tried TS before . which is weird, the extension of the file is still .js .

https://ibb.co/JyJcy7M     

https://ibb.co/9hkn0ct

- OS : Windows 10

any idea ? thought it was simple by reading the docs :/

**Comment by shifuchen98** [comment]
> ERROR #98123 WEBPACK

Same error occurring to me. Seems there is some TypeScript code appearing inside `.js` files, and the build program attempted to interpret them as JavaScript code, which led to the error.

**Comment by Jeffreyhung** [comment]
I think it is due to the last update of Gatsby, I encountered the same error message when I update the following two packages on my forked repo.
```
"gatsby": ^2.30.1 > ^2.31.0,
"gatsby-cli": ^2.17.1 > ^2.18.0
```

The changes are made only two days ago #873

**Comment by hyun-cho** [comment]
I found same error,

I temporarily fixed this issue with this link 

`[here](https://github.com/gatsbyjs/gatsby/issues/29105#issuecomment-764867072)`

**Comment by nebulousdots** [comment]
This worked for me:
"gatsby": ^2.30.1 > ^2.31.0, (in package.json)
"gatsby-cli": ^2.17.1 > ^2.18.0 (installing this old version)

**Comment by sungpyocho** [comment]
For me, updating gatsby version in package.json to `"gatsby": "^2.32.2"` fixed this issue.
It seems that gatsby version v.2.32.1 or higher fixes this problem, according to the [link](https://github.com/gatsbyjs/gatsby/issues/29105#issuecomment-773196071) by @hyun-cho.

**Comment by Jeffreyhung** [comment]
Can confirm with @sungpyocho, upgrading Gatsby to 2.32.2 fixed the issue
