### ISSUE TITLE
Flow parsing error

### ISSUE THREAD

**Issue by flipchart** [alxshelepenok/gatsby-starter-lumen#881]
**Describe the bug**
Getting an error with the Flow types when runing `gatsby develop` on a brand new project. One of the errors is `error  Parsing error: Unexpected token :` but I get a whole mess of them for each of the JS files that have Flow types in them. 

**To Reproduce**
1. `gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumen`
2. `cd blog`
3. `gatsby develop`

**Expected behavior**
Compile without error

**Screenshots**
```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


C:\work\github\blog\src\components\Feed\Feed.js
  4:13  error  Parsing error: Unexpected token {

✖ 1 problem (1 error, 0 warnings)


File: src\components\Feed\Feed.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


C:\work\github\blog\src\components\Icon\Icon.js
  5:6  error  Parsing error: Unexpected token Props

✖ 1 problem (1 error, 0 warnings)


File: src\components\Icon\Icon.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


C:\work\github\blog\src\components\Layout\Layout.js
  4:13  error  Parsing error: Unexpected token {

✖ 1 problem (1 error, 0 warnings)


File: src\components\Layout\Layout.js
```

**Additional context**
`gatsby info` output:
```
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.14
  Browsers:
    Chrome: 88.0.4324.104
    Edge: Spartan (44.18362.449.0)
  npmGlobalPackages:
    gatsby-cli: 2.18.0
```

I do  have python3 installed, but gatsby obviously doesn't pick it up (if that's important). The packages were installed with yarn, but I tried using WSL with npm and got the same issue.

**Comment by ferdigokdemir** [comment]
same error!

<img width="968" alt="Screen Shot 2021-01-29 at 23 33 04" src="https://user-images.githubusercontent.com/23097465/106324521-5706bb80-628a-11eb-83e6-19c8dc7049b1.png">

**Comment by sevensidedmarble** [comment]
I'm having this problem too. It happens on older tags of the repo too, which leads me to believe it may be a dependency?

```
File: src/components/Sidebar/Author/Author.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/marble/dev/blog/src/components/Sidebar/Contacts/Contacts.js
  7:6  error  Parsing error: Unexpected token Props

✖ 1 problem (1 error, 0 warnings)


File: src/components/Sidebar/Contacts/Contacts.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/marble/dev/blog/src/components/Sidebar/Copyright/Copyright.js
  5:6  error  Parsing error: Unexpected token Props

✖ 1 problem (1 error, 0 warnings)


File: src/components/Sidebar/Copyright/Copyright.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/marble/dev/blog/src/components/Sidebar/Menu/Menu.js
  6:6  error  Parsing error: Unexpected token Props

✖ 1 problem (1 error, 0 warnings)


File: src/components/Sidebar/Menu/Menu.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/marble/dev/blog/src/components/Sidebar/Sidebar.js
  10:6  error  Parsing error: Unexpected token Props

✖ 1 problem (1 error, 0 warnings)


File: src/components/Sidebar/Sidebar.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/marble/dev/blog/src/templates/category-template.js
  10:13  error  Parsing error: Unexpected token {

✖ 1 problem (1 error, 0 warnings)


File: src/templates/category-template.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/marble/dev/blog/src/templates/index-template.js
  10:13  error  Parsing error: Unexpected token {

✖ 1 problem (1 error, 0 warnings)


File: src/templates/index-template.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/marble/dev/blog/src/templates/page-template.js
  8:13  error  Parsing error: Unexpected token {

✖ 1 problem (1 error, 0 warnings)


File: src/templates/page-template.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/marble/dev/blog/src/templates/post-template.js
  7:13  error  Parsing error: Unexpected token {

✖ 1 problem (1 error, 0 warnings)


File: src/templates/post-template.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/marble/dev/blog/src/templates/tag-template.js
  10:13  error  Parsing error: Unexpected token {

✖ 1 problem (1 error, 0 warnings)


File: src/templates/tag-template.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/marble/dev/blog/src/utils/get-contact-href.js
  2:29  error  Parsing error: Unexpected token :

✖ 1 problem (1 error, 0 warnings)


File: src/utils/get-contact-href.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/marble/dev/blog/src/utils/get-icon.js
  4:22  error  Parsing error: Unexpected token :

✖ 1 problem (1 error, 0 warnings)


File: src/utils/get-icon.js

failed Building development bundle - 12.985s

```

**Comment by anunayasri** [comment]
I am not sure about the fix. As a workaround, you can use the tag `3.0.5`.

```sh
git clone https://github.com/alxshelepenok/gatsby-starter-lumen.git myapp
cd myapp
git checkout tags/3.0.5

# Run gatsby commands now
gatsby develop
```

**Comment by ferdigokdemir** [comment]
@anunayasri yes working!

**Comment by RobertBernstein** [comment]
> ```shell
> git checkout tags/3.0.5
> ```

This worked, but I had to run `npm install` before I could run `gatsby develop`.  Then it worked correctly.  Thanks for the help!

**Comment by anunayasri** [comment]
> This worked, but I had to run `npm install` before I could run `gatsby develop`. Then it worked correctly. Thanks for the help!

Oh yeah. Forgot to mention it. Updated my previous comment. Thanks :)

**Comment by mancku** [comment]
Same error here, following the same steps

>System
&nbsp;&nbsp;&nbsp;&nbsp; OS: Microsoft Windows [Version 10.0.19042.746]
&nbsp;&nbsp;&nbsp;&nbsp; WSL: 5.4.72-microsoft-standard-WSL2
&nbsp;&nbsp;&nbsp;&nbsp;	Ubuntu Version: 20.04.1 LTS (Focal Fossa)
&nbsp;&nbsp;&nbsp;&nbsp;	CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Node
&nbsp;&nbsp;&nbsp;&nbsp;	Node: 14.15.4
&nbsp;&nbsp;&nbsp;&nbsp;	npm: 6.14.10
&nbsp;&nbsp;&nbsp;&nbsp;	Gatsby CLI version: 2.19.0
&nbsp;&nbsp;&nbsp;&nbsp;	Gatsby version: 2.32.0


> ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Feed/Feed.js
  > 4:13  error  Parsing error: Unexpected token {
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Feed/Feed.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Icon/Icon.js
  > 5:6  error  Parsing error: Unexpected token Props
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Icon/Icon.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Layout/Layout.js
  > 4:13  error  Parsing error: Unexpected token {
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Layout/Layout.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Page/Page.js
  > 4:6  error  Parsing error: Unexpected token Props
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Page/Page.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Pagination/Pagination.js
  > 8:6  error  Parsing error: Unexpected token Props
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Pagination/Pagination.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Post/Comments/Comments.js
  > 6:6  error  Parsing error: Unexpected token Props
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Post/Comments/Comments.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Post/Content/Content.js
  > 5:6  error  Parsing error: Unexpected token Props
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Post/Content/Content.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Post/Meta/Meta.js
  > 5:6  error  Parsing error: Unexpected token Props
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Post/Meta/Meta.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Post/Post.js
  > 10:13  error  Parsing error: Unexpected token {
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Post/Post.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Post/Tags/Tags.js
  > 6:6  error  Parsing error: Unexpected token Props
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Post/Tags/Tags.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Sidebar/Author/Author.js
  > 6:6  error  Parsing error: Unexpected token Props
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Sidebar/Author/Author.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Sidebar/Contacts/Contacts.js
  > 7:6  error  Parsing error: Unexpected token Props
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Sidebar/Contacts/Contacts.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Sidebar/Copyright/Copyright.js
  > 5:6  error  Parsing error: Unexpected token Props
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Sidebar/Copyright/Copyright.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Sidebar/Menu/Menu.js
  > 6:6  error  Parsing error: Unexpected token Props
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Sidebar/Menu/Menu.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/components/Sidebar/Sidebar.js
  > 10:6  error  Parsing error: Unexpected token Props
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/components/Sidebar/Sidebar.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/templates/category-template.js
  > 10:13  error  Parsing error: Unexpected token {
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/templates/category-template.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/templates/index-template.js
  > 10:13  error  Parsing error: Unexpected token {
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/templates/index-template.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/templates/page-template.js
  > 8:13  error  Parsing error: Unexpected token {
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/templates/page-template.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/templates/post-template.js
  > 7:13  error  Parsing error: Unexpected token {
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/templates/post-template.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/templates/tag-template.js
  > 10:13  error  Parsing error: Unexpected token {
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/templates/tag-template.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/utils/get-contact-href.js
  > 2:29  error  Parsing error: Unexpected token :
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/utils/get-contact-href.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> 
> /home/mancku/dev/mancku-blog/src/utils/get-icon.js
  > 4:22  error  Parsing error: Unexpected token :
> 
> ✖ 1 problem (1 error, 0 warnings)
> 
> 
> File: src/utils/get-icon.js
> 
> failed Building development bundle - 15.361s
