### ISSUE TITLE
This Gatsby starter does not work out of the box and generates errors: Field "socialImage" must not have a selection since type "String" has no subfields.

### ISSUE THREAD

**Issue by jvonruden** [alxshelepenok/gatsby-starter-lumen#890]
On 2/6/2021 on Windows 10 Computer attempt to use starter by following [readme.md](https://github.com/alxshelepenok/gatsby-starter-lumen/blob/master/README.md) instructions exactly. You will be greeted with these errors "Field "socialImage" must not have a selection since type "String" has no subfields."

This Gatsby starter does not work out of the box and generates errors.

Reproduction setups:
1. gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumen
2. cd blog
3. gatsby develop
4. Open site is now running at http://localhost:8000 
5. Observe webpage full of GraphQL "socialImage" errors.

**Error Output:** 
`Failed to compile.

There was an error in your GraphQL query:
      Field "socialImage" must not have a selection since type "String" has no subfields.

      This can happen if you e.g. accidentally added { } to the field "socialImage". If you didn't expect "socialImage" to be of type "String" make sure that your input source and/or plugin is correct.
      However, if you expect "value" to exist, the field might be accessible in another subfield. Please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have.

      It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned
      "dummy content". Visit our docs to learn how you can define the schema for "undefined":
      https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Gatsby/blog/src/templates/page-template.js

There was an error in your GraphQL query:

      Field "socialImage" must not have a selection since type "String" has no subfields.

      This can happen if you e.g. accidentally added { } to the field "socialImage". If you didn't expect "socialImage" to be of type "String" make sure that your input source and/or plugin is correct.
      However, if you expect "value" to exist, the field might be accessible in another subfield. Please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have.

      It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned
      "dummy content". Visit our docs to learn how you can define the schema for "undefined":
      https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: /Gatsby/blog/src/templates/post-template.js
`

**Comment by bretmlw** [comment]
Hi! Are you able to share exactly what you did to fix this? Assuming that you did as it's closed and I'm facing the same issue, with other fixes in the issues not working in my case.

**Comment by sanhuesoft** [comment]
> Hi! Are you able to share exactly what you did to fix this? Assuming that you did as it's closed and I'm facing the same issue, with other fixes in the issues not working in my case.

Same issue here.

**Comment by marcopinato** [comment]
Just leaving this here for posterity, in case it helps someone.

I had a similar issue, where I was able to build the project locally but then it failed on Netlify. Turns out I had specified a non-existent `socialUrl` path in one of the pages, so make sure to double-check every path.
