### ISSUE TITLE
"ERROR #98123  WEBPACK" on JS generation

### ISSUE THREAD

**Issue by bretmlw** [alxshelepenok/gatsby-starter-lumen#909]
**Describe the bug**
When trying to run `gatsby develop` from a fresh pull of the starter, the following error is shown:

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

PostCSS plugin postcss-pxtorem requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users

File: XXXXXXXXXXXXXXXXXXXXX
```

**To Reproduce**
1. Create new site through `gatsby new gatsby-starter-lumen https://github.com/alxshelepenok/gatsby-starter-lumen`
2. Start development environment by with `gatsby develop`
3. See error

**Expected behavior**
I'd expect it to generate and start successfully. 

**Additional context**
npm: 6.14.11
node: 12.21.0
OS: Debian 10
Also fails to build on CloudFlare pages when attempted with the same error.

**Comment by bretmlw** [comment]
As I was typing this out, I attempted again and got it running with `npm install postcss postcss-pxtorem gatsby-plugin-postcss@3.0.0` after the initial pull of the base repo. Thought I'd still post the above error just in case others search for it!

**Comment by hieunguyena6** [comment]
![image](https://user-images.githubusercontent.com/41582482/110423071-024d3080-80d3-11eb-91ae-2523a838452f.png)
Same issue, but  `npm install postcss postcss-pxtorem gatsby-plugin-postcss@3.0.0 ` is not working with me !

**Comment by tbezman** [comment]
@bretmlw `yarn add postcss-pxtorem@5.1.1` worked for me. Looks like the most recent version of this postcss plugin is the culprit. Recommend @alxshelepenok to checkout the latest master / netlify build. They're both broken for me

**Comment by tbezman** [comment]
@hieunguyena6 Meant to tag you in my first comment if you're still looking for a solution

**Comment by tbezman** [comment]
Mentioned how to fix this in a blog post https://bezcode.com/posts/how-i-published-this-site
