### ISSUE TITLE
PostCSS plugin postcss-pxtorem requires PostCSS 8

### ISSUE THREAD

**Issue by intrepid-ishan** [alxshelepenok/gatsby-starter-lumen#913]
When I run `gatsby develop`, I am getting error as **PostCSS plugin postcss-pxtorem requires PostCSS 8**

I tried to uninstall gatsby and reinstall.

Also I  recloned and tried again, nothing worked.

How to solve this?

**Comment by bretmlw** [comment]
You'll want to install postcss-pxtorem@5.1.1 (`npm install postcss-pxtorem@5.1.1`) and use that in your install instead and this should work fine!

**Comment by a-c-m** [comment]
This does fix the issue - but not sure this should be closed. Out of the box, without this fix, it does not work.

**Comment by intrepid-ishan** [comment]
> This does fix the issue - but not sure this should be closed. Out of the box, without this fix, it does not work.

Ya it doesn't work without this fix

**Comment by intrepid-ishan** [comment]
Reopened! @a-c-m
