### ISSUE TITLE
Im new to gatsby please tell me how to deploy on github pages

### ISSUE THREAD

**Issue by kaustubhk24** [alxshelepenok/gatsby-starter-lumen#918]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alxshelepenok** [comment]
Thank you for your feedback. The starter has been updated to the new version and the bug has probably been fixed.
