### ISSUE TITLE
Unable to develop Gatsby site on local machine

### ISSUE THREAD

**Issue by Trushar10** [alxshelepenok/gatsby-starter-lumen#934]
I am new to gatsby development and trying to learn the development of gatsby sites. While downloading the starter for the first time did not give any vulnerabilities or any error. But for the past 2 days, I am getting vulnerabilities and errors.  and unable to develop on the local machine.

Do the vulnerabilities affects the site? If deploy with netlify the site works without any error. 

Windows 10

Gatsby CLI version: 3.5.0
Gatsby version: 2.32.13

Node js version: 14.16.1

npm version: 6.14.12

While using `gatsby develop` I am getting some errors which are below.

`PS D:\Quick access\Documents\GitHub\gatsby-starter-lumen> gatsby develop
success open and validate gatsby-configs - 0.797s
success load plugins - 4.771s
success onPreInit - 0.082s
success initialize cache - 0.016s
success copy gatsby files - 0.341s
success onPreBootstrap - 0.052s
success createSchemaCustomization - 0.262s
success Checking for changed pages - 0.003s
success source and transform nodes - 0.835s
success building schema - 0.794s
info Total nodes: 201, SitePage nodes: 28 (use --verbose for breakdown)
success createPages - 0.212s
success Checking for changed pages - 0.003s
success createPagesStatefully - 0.160s
success update schema - 0.068s
success write out redirect data - 0.079s
success Build manifest and related icons - 0.263s
success onPostBootstrap - 0.281s
info bootstrap finished - 18.311s
success onPreExtractQueries - 0.002s

 ERROR #85922  GRAPHQL

There was an error in your GraphQL query:

      Field "socialImage" must not have a selection since type "String" has no subfields.

      This can happen if you e.g. accidentally added { } to the field "socialImage". If you didn't expect "socialImage" to be of type "String"    
make sure that your input source and/or plugin is correct.
      However, if you expect "value" to exist, the field might be accessible in another subfield. Please try your query in GraphiQL and use the   
GraphiQL explorer to see which fields you can query and what shape they have.

      It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned   
      "dummy content". Visit our docs to learn how you can define the schema for "undefined":
      https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src\templates\page-template.js:43:21

 ERROR #85922  GRAPHQL

There was an error in your GraphQL query:

      Field "socialImage" must not have a selection since type "String" has no subfields.

      This can happen if you e.g. accidentally added { } to the field "socialImage". If you didn't expect "socialImage" to be of type "String"    
make sure that your input source and/or plugin is correct.
      However, if you expect "value" to exist, the field might be accessible in another subfield. Please try your query in GraphiQL and use the   
GraphiQL explorer to see which fields you can query and what shape they have.

      It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned   
      "dummy content". Visit our docs to learn how you can define the schema for "undefined":
      https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: src\templates\post-template.js:43:21

failed extract queries from components - 1.467s
success write out requires - 0.162s
success run page queries - 0.060s - 2/2 33.39/s
 DONE  Compiled successfully in 23134ms                                                                                                11:54:23 pm⠀
 I  Netlify CMS is running at http://localhost:8000/admin/
⠀
You can now view gatsby-starter-lumen in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 39.588s
`

and in browser I am getting this:
`Failed to compile.

There was an error in your GraphQL query:
      Field "socialImage" must not have a selection since type "String" has no subfields.

      This can happen if you e.g. accidentally added { } to the field "socialImage". If you didn't expect "socialImage" to be of type "String" make sure that your input source and/or plugin is correct.
      However, if you expect "value" to exist, the field might be accessible in another subfield. Please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have.

      It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned
      "dummy content". Visit our docs to learn how you can define the schema for "undefined":
      https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: D:/Quick access/Documents/GitHub/gatsby-starter-lumen/src/templates/page-template.js

There was an error in your GraphQL query:

      Field "socialImage" must not have a selection since type "String" has no subfields.

      This can happen if you e.g. accidentally added { } to the field "socialImage". If you didn't expect "socialImage" to be of type "String" make sure that your input source and/or plugin is correct.
      However, if you expect "value" to exist, the field might be accessible in another subfield. Please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have.

      It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned
      "dummy content". Visit our docs to learn how you can define the schema for "undefined":
      https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: D:/Quick access/Documents/GitHub/gatsby-starter-lumen/src/templates/post-template.js`

**Comment by Jeffreyhung** [comment]
There's currently a workaround in issue #777 (https://github.com/alxshelepenok/gatsby-starter-lumen/issues/777#issuecomment-736197742)
