### ISSUE TITLE
GraphQL Error message comes out when create a new site with this starter

### ISSUE THREAD

**Issue by Puterism** [alxshelepenok/gatsby-starter-lumen#954]
**Describe the bug**
When create a new site with this Gatsby starter and open the develop server by `gatsby develop`, I got the following GraphQL error message and failed to compile.

```
 ERROR #85922  GRAPHQL

There was an error in your GraphQL query:

      Field "socialImage" must not have a selection since type "String" has no subfields.

      This can happen if you e.g. accidentally added { } to the field "socialImage". If you didn't expect
"socialImage" to be of type "String" make sure that your input source and/or plugin is correct.
      However, if you expect "value" to exist, the field might be accessible in another subfield. Please try
 your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they
have.

      It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way
you don't have to add the mentioned
      "dummy content". Visit our docs to learn how you can define the schema for "undefined":
      https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
```

**To Reproduce**
1. Create a new site with Gatsby CLI.
```base
gatsby new blog https://github.com/alxshelepenok/gatsby-starter-lumen
```

2. Start the development server.
```bash
cd blog
gatsby develop
```

3. Get the error message.
![image](https://user-images.githubusercontent.com/2542730/122664267-6b1c6c80-d1db-11eb-9dce-f27941bea43a.png)

**Expected behavior**
When the development server is opened, building development bundle will finish successfully. Also, the page will be able to open in the browser.

**Desktop:**
 - OS: Windows 10 64bit
 - Browser: Brave
 - Version 1.25.73 Chromium: 91.0.4472.106

**Additional context**
Currently, I can't create a new site with this starter because of this problem, so I checked the code file where the error caused.

```graphql
query PostBySlug($slug: String!) {
  markdownRemark(fields: { slug: { eq: $slug } }) {
    id
    html
    fields {
      slug
      tagSlugs
    }
    frontmatter {
      date
      description
      tags
      title
      socialImage {
        publicURL # ???
      }
    }
  }
}
```

I have no idea why there is `publicURL` in the query of the code from `templates/post-template.js` and `templates/page-template.js`.
There is no related frontmatter of `publicURL` in sample markdown docs in `contents` directory.
So I can't understand about `publicURL` subfield of `socialImage`.
To check, I deleted all subfield queries about `publicURL`, then it works. Is there anything I missed about `publicURL`?

**Comment by hoangmnsd** [comment]
I run in the same problem

**Comment by dariusz-wozniak** [comment]
See the https://github.com/alxshelepenok/gatsby-starter-lumen/issues/761 thread.

This helped me solving the issue:

>     * Install `gatsby-plugin-netlify-cms-paths`
>     * add `gatsby-plugin-netlify-cms-paths` BEFORE gatsby-transformer-remark to `gatsby-config.js`

/cc @Puterism, @hoangmnsd

**Comment by Puterism** [comment]
Oh, it was already an issue. Thank you for letting me know 😃 

But `gatsby-plugin-netlify-cms-paths` was archived and this starter was not used this package before.
So I don't think it's a good way.
https://github.com/escaladesports/legacy-gatsby-plugin-netlify-cms-paths

**Comment by Puterism** [comment]
I found an issue and PR. #741, #755. Maybe I think this PR is the cause.
For some reason, the maintainer added some query code with `publicURL`. It said for `upgrade gatsby-remark-relative-images`.
`socialImage` link should be on twitter card and opengraph, but `gatsby-remark-relative-images` change image path to relative path when `remark` is working. e.g. `../../static/media/image-1.png`

There will be a problem where the path is wrong. Like this,

![image](https://user-images.githubusercontent.com/2542730/141715050-9c0168cb-c096-4d0d-8cfa-e8b3f4d9faaa.png)

It's a conflict problem between `gatsby-remark-relative-images` and `socialImage` path problem, I guess.

So I think `publicURL` mean to enter the full path including the URI. But it's just my opinion. Maintainer should be explain about this `publicURL` means.

**Comment by Yz-2** [comment]
Add this code `socialImage: { publicURL: ''}` to `content/post/xxx.md` and  `content/pages/xxx.md` .
One for each.

**example**

`/content/post/xxx.md` and `/content/pages/xxx.md`

```
---
template: page
title: test
slug: test
+ socialImage: { publicURL: ''}
draft: false
---

test
```

This is a temporary solution.

**Comment by alxshelepenok** [comment]
Thank you for your feedback. The starter has been updated to the new version and the bug has probably been fixed. Feel free to reopen the issue.
