### ISSUE TITLE
Posts out of order

### ISSUE THREAD

**Issue by twhite96** [alxshelepenok/gatsby-starter-lumen#97]
Previewing my site in dev, the posts and dates are in order. However, when I deploy to Netlify, the posts are out of order, refreshing the page puts them in a different order, and triggering a new deploy puts them in yet another order. I don't know if this is on Netlify or what, but my frontmatter is correct and folder structures are also correct.

**Comment by jamischarles** [comment]
I'm seeing this issue as well. What's strange for me, is that it changes between local dev builds. I'm curious what timestamp is used for the order. Whether it uses frontmatter timestamp or timestamp that's in the filename

**Comment by twhite96** [comment]
> I'm seeing this issue as well. What's strange for me, is that it changes between local dev builds. I'm curious what timestamp is used for the order. Whether it uses frontmatter timestamp or timestamp that's in the filename

This was an issue with the gatsby-remark...I don't remember which plugin but it was a core plugin. Update your plugins and the issue goes away.

**Comment by twhite96** [comment]
Closing this as it is a core Gatsby problem and not this starter.
