### ISSUE TITLE
A matrix table of Tags, and search box for content

### ISSUE THREAD

**Issue by hoangmnsd** [alxshelepenok/gatsby-starter-lumen#971]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when going to a Blog but can not find/search something I need on that Blog

**Describe the solution you'd like**
First is a Matrix table of Tags will help visitors see what topic that was written a lot in that blog.
Second is a Search box, help visitor to find what he/she is interesting faster? (instead of click on `Next Page`)

![image](https://user-images.githubusercontent.com/12986552/126927167-320572af-91a7-4eb5-b859-609597b10cbc.png)

**Comment by alxshelepenok** [comment]
Thank you for your feedback. The starter has been updated to the new version and the bug has probably been fixed. Feel free to reopen the issue.

**Comment by hungdev** [comment]
@alxshelepenok hi, I think this bug shouldn't close. We still don't have a search box for content. It's a great feature for a blog. It helps users easy to find a post.
