### ISSUE TITLE
Question - Modifying Post URL

### ISSUE THREAD

**Issue by donvito** [alxshelepenok/gatsby-starter-lumen#974]
Hi, in the latest version of the code,

How do I configure the post url to be:
http://localhost:8000/my-post-slug

Instead of this:
http://localhost:8000/posts/my-post-slug

Basically, removing "/posts" in the URL. 

Thank you!

**Comment by donvito** [comment]
My friend found the issue. Just for reference in case someone needs this.

https://github.com/donvito/melvinvivas-com-blog/commit/c1a131914e489135cffade1c02e2e4b96bccecd4

**Comment by pietrzakadrian** [comment]
That's not enough. You still need to edit this code in gatsby-config.js:

```
 serialize: ({ query: { site, allMarkdownRemark } }) =>
              allMarkdownRemark.edges.map((edge) => ({
                ...edge.node.frontmatter,
                description: edge.node.frontmatter.description,
                date: edge.node.frontmatter.date,
                url: site.siteMetadata.site_url,
                guid: site.siteMetadata.site_url,
                custom_elements: [{ "content:encoded": edge.node.html }],
              })),
```
