### ISSUE TITLE
Posts be a sub-page and page be the index

### ISSUE THREAD

**Issue by fabriziofeitosa** [alxshelepenok/gatsby-starter-lumen#990]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
You could have the option that if you create an "index.md" it will be used as the homepage and the posts will go to "/blog".

**Additional context**
I would like to be able to put one of the pages created as the site's index and the posts go to "/blog".

**Comment by alxshelepenok** [comment]
Thank you for your feedback. The starter has been updated to the new version and the bug has probably been fixed. Feel free to reopen the issue.
